2019-03-29 10:39:50.640 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 1a600758773142aaa6f13e7591d520ca __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:39:50.646 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: b5d2ae3bd9ed47638162f88a08fc8ebc exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:50.678 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b5d2ae3bd9ed47638162f88a08fc8ebc __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:39:50.680 18469 DEBUG oslo_concurrency.lockutils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825" acquired by "nova.compute.manager.do_terminate_instance" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:39:50.681 18469 DEBUG oslo_concurrency.lockutils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._clear_events" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:39:50.681 18469 DEBUG oslo_concurrency.lockutils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._clear_events" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:39:50.682 18469 WARNING nova.image.glance [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:39:50.685 18469 INFO nova.compute.manager [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Terminating instance
2019-03-29 10:39:50.686 18469 WARNING nova.image.glance [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:39:50.689 18469 DEBUG nova.compute.manager [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Start destroying the instance on the hypervisor. _shutdown_instance /usr/lib/python2.7/site-packages/nova/compute/manager.py:2248
2019-03-29 10:39:50.902 18469 INFO nova.virt.libvirt.driver [-] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance destroyed successfully.
2019-03-29 10:39:50.904 18469 DEBUG nova.virt.libvirt.vif [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] vif_type=ovs instance=Instance(access_ip_v4=None,access_ip_v6=None,architecture='x86_64',auto_disk_config=True,availability_zone='nova',cell_name=None,cleaned=True,config_drive='True',created_at=2019-03-29T02:02:33Z,default_ephemeral_device=None,default_swap_device=None,deleted=False,deleted_at=None,device_metadata=<?>,disable_terminate=False,display_description='vm001',display_name='vm001',ec2_ids=<?>,ephemeral_gb=0,ephemeral_key_uuid=None,fault=<?>,flavor=Flavor(1),host='com58',hostname='vm001',id=24,image_ref='',info_cache=InstanceInfoCache,instance_type_id=1,kernel_id='',key_data=None,key_name=None,keypairs=<?>,launch_index=0,launched_at=2019-03-29T02:34:01Z,launched_on='com58',locked=False,locked_by=None,memory_mb=512,metadata={},migration_context=<?>,new_flavor=None,node='com58',numa_topology=None,old_flavor=None,os_type=None,pci_devices=PciDeviceList,pci_requests=<?>,power_state=1,progress=0,project_id='d4bbd972ca1b463ba028ccd1df983917',ramdisk_id='',reservation_id='r-x56iqcqr',root_device_name='/dev/vda',root_gb=1,security_groups=SecurityGroupList,services=<?>,shutdown_terminate=False,system_metadata={boot_roles='admin',clean_attempts='2',image_architecture='x86_64',image_base_image_ref='',image_min_disk='1',image_min_ram='0'},tags=<?>,task_state='deleting',terminated_at=None,updated_at=2019-03-29T02:37:19Z,user_data=None,user_id='9e9e53917dda421083fa6af425c6bfbf',uuid=f5a19c94-1a45-4ea0-9386-77c10705c825,vcpu_model=<?>,vcpus=1,vm_mode=None,vm_state='active') vif={"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": true, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} unplug /usr/lib/python2.7/site-packages/nova/virt/libvirt/vif.py:966
2019-03-29 10:39:50.905 18469 DEBUG nova.network.os_vif_util [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converting VIF {"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": true, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:413
2019-03-29 10:39:50.907 18469 DEBUG nova.network.os_vif_util [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converted object VIFBridge(active=True,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:425
2019-03-29 10:39:50.908 18469 DEBUG os_vif [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Unplugging vif VIFBridge(active=True,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') unplug /usr/lib/python2.7/site-packages/os_vif/__init__.py:112
2019-03-29 10:39:50.913 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'vif_plug_ovs.linux_net.delete_bridge', (u'qbrb3249515-3a', 'qvbb3249515-3a'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:50.913 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl delif qbrb3249515-3a qvbb3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:50.929 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl delif qbrb3249515-3a qvbb3249515-3a" returned: 0 in 0.015s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:50.929 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qbrb3249515-3a down out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:50.937 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qbrb3249515-3a down" returned: 0 in 0.009s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:50.937 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl delbr qbrb3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:50.953 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl delbr qbrb3249515-3a" returned: 0 in 0.017s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:50.954 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:50.955 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'vif_plug_ovs.linux_net.delete_ovs_vif_port', (u'br-int', 'qvob3249515-3a'), {'timeout': 120}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:50.956 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ovs-vsctl --timeout=120 -- --if-exists del-port br-int qvob3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:50.979 18469 DEBUG oslo.privsep.daemon [-] CMD "ovs-vsctl --timeout=120 -- --if-exists del-port br-int qvob3249515-3a" returned: 0 in 0.023s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:50.980 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link delete qvob3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:51.001 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link delete qvob3249515-3a" returned: 0 in 0.022s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:51.001 18469 DEBUG oslo.privsep.daemon [-] Net device removed: 'qvob3249515-3a' out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:51.002 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:51.002 18469 INFO os_vif [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Successfully unplugged vif VIFBridge(active=True,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a')
2019-03-29 10:39:51.003 18469 DEBUG nova.virt.libvirt.volume.iscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] calling os-brick to detach iSCSI Volume disconnect_volume /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/iscsi.py:72
2019-03-29 10:39:51.004 18469 DEBUG os_brick.initiator.connectors.iscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> disconnect_volume: call u"{'args': (<os_brick.initiator.connectors.iscsi.ISCSIConnector object at 0x5ae9b50>, {u'device_path': u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0', u'target_discovered': False, u'encrypted': False, u'qos_specs': None, u'target_iqn': u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_portal': u'172.30.126.56:3260', u'volume_id': u'78a56ddc-ee21-4278-991e-17b30d68fa6e', u'auth_password': u'***', u'target_lun': 0, u'access_mode': u'rw', u'auth_username': u'PutS9jPtTsLadXTr42qr', u'auth_method': u'CHAP'}, None), 'kwargs': {}}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:39:51.004 18469 DEBUG oslo_concurrency.lockutils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "connect_volume" acquired by "os_brick.initiator.connectors.iscsi.disconnect_volume" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:39:51.005 18469 DEBUG os_brick.initiator.linuxscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Flushing IO for device /dev/sdb flush_device_io /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:146
2019-03-29 10:39:51.006 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'os_brick.privileged.rootwrap.execute_root', ('blockdev', '--flushbufs', u'/dev/sdb'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:51.006 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): blockdev --flushbufs /dev/sdb out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:51.010 18469 DEBUG oslo.privsep.daemon [-] CMD "blockdev --flushbufs /dev/sdb" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:51.010 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:51.010 18469 DEBUG os_brick.initiator.linuxscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Remove SCSI device /dev/sdb with /sys/block/sdb/device/delete remove_scsi_device /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:69
2019-03-29 10:39:51.011 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'os_brick.privileged.rootwrap.execute_root', ('tee', '-a', u'/sys/block/sdb/device/delete'), {'process_input': '1'}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:51.011 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): tee -a /sys/block/sdb/device/delete out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:51.015 18469 DEBUG oslo.privsep.daemon [-] CMD "tee -a /sys/block/sdb/device/delete" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:51.015 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, ('1', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:51.015 18469 DEBUG os_brick.initiator.linuxscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Checking to see if SCSI volume /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 has been removed. wait_for_volume_removal /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:77
2019-03-29 10:39:51.016 18469 DEBUG os_brick.initiator.linuxscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 still exists. wait_for_volume_removal /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:79
2019-03-29 10:39:51.016 18469 DEBUG os_brick.utils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Failed attempt 1 _print_stop /usr/lib/python2.7/site-packages/os_brick/utils.py:45
2019-03-29 10:39:51.016 18469 DEBUG os_brick.utils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Have been at this for 0.0 seconds _print_stop /usr/lib/python2.7/site-packages/os_brick/utils.py:47
2019-03-29 10:39:51.017 18469 DEBUG os_brick.utils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Sleeping for 2 seconds _backoff_sleep /usr/lib/python2.7/site-packages/os_brick/utils.py:40
2019-03-29 10:39:53.018 18469 DEBUG os_brick.initiator.linuxscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Checking to see if SCSI volume /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 has been removed. wait_for_volume_removal /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:77
2019-03-29 10:39:53.019 18469 DEBUG os_brick.initiator.linuxscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] SCSI volume /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 has been removed. wait_for_volume_removal /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:83
2019-03-29 10:39:53.020 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.startup', '-v', 'manual'), {'attempts': 1, 'check_exit_code': (0, 21, 255), 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:53.021 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.startup -v manual out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:53.028 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.startup -v manual" returned: 0 in 0.008s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:53.029 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:53.029 18469 DEBUG os_brick.initiator.connectors.iscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.startup', '-v', 'manual'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:39:53.030 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--logout'), {'attempts': 1, 'check_exit_code': (0, 21, 255), 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:53.030 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --logout out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:53.037 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --logout" returned: 0 in 0.007s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:53.038 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, ('Logging out of session [sid: 10, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260]\nLogout of [sid: 10, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] successful.\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:53.038 18469 DEBUG os_brick.initiator.connectors.iscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--logout',): stdout=Logging out of session [sid: 10, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260]
Logout of [sid: 10, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] successful.
 stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:39:53.039 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'delete'), {'attempts': 5, 'check_exit_code': (0, 21, 255), 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:53.039 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op delete out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:53.043 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op delete" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:53.043 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:53.043 18469 DEBUG os_brick.initiator.connectors.iscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'delete'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:39:53.044 18469 DEBUG oslo_concurrency.lockutils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "connect_volume" released by "os_brick.initiator.connectors.iscsi.disconnect_volume" :: held 2.039s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:39:53.044 18469 DEBUG os_brick.initiator.connectors.iscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== disconnect_volume: return (2039ms) None trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:39:53.044 18469 DEBUG nova.virt.libvirt.volume.iscsi [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Disconnected iSCSI Volume vda disconnect_volume /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/iscsi.py:78
2019-03-29 10:39:53.045 18469 DEBUG oslo_concurrency.processutils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): mv /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825 /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_del execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:39:53.055 18469 DEBUG oslo_concurrency.processutils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "mv /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825 /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_del" returned: 0 in 0.010s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:39:53.056 18469 INFO nova.virt.libvirt.driver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Deleting instance files /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_del
2019-03-29 10:39:53.056 18469 INFO nova.virt.libvirt.driver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Deletion of /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_del complete
2019-03-29 10:39:53.060 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 45ce019e3e5b41d59516e166a337cacf exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:53.161 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 5ba3b984f56949538414b7428ec0cbf0 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:39:53.163 18469 DEBUG nova.compute.manager [req-e2fc7216-c156-4cbc-959b-df90cc2f78f5 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-vif-unplugged-b3249515-3aab-439f-ba9c-bc498756871a external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:39:53.164 18469 DEBUG oslo_concurrency.lockutils [req-e2fc7216-c156-4cbc-959b-df90cc2f78f5 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:39:53.164 18469 DEBUG nova.compute.manager [req-e2fc7216-c156-4cbc-959b-df90cc2f78f5 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:350
2019-03-29 10:39:53.164 18469 DEBUG oslo_concurrency.lockutils [req-e2fc7216-c156-4cbc-959b-df90cc2f78f5 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._pop_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:39:53.165 18469 DEBUG nova.compute.manager [req-e2fc7216-c156-4cbc-959b-df90cc2f78f5 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] No waiting events found dispatching network-vif-unplugged-b3249515-3aab-439f-ba9c-bc498756871a pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:366
2019-03-29 10:39:53.165 18469 WARNING nova.compute.manager [req-e2fc7216-c156-4cbc-959b-df90cc2f78f5 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received unexpected event network-vif-unplugged-b3249515-3aab-439f-ba9c-bc498756871a for instance
2019-03-29 10:39:53.186 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 45ce019e3e5b41d59516e166a337cacf __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:39:53.191 18469 INFO nova.compute.manager [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Took 2.50 seconds to destroy the instance on the hypervisor.
2019-03-29 10:39:53.192 18469 DEBUG nova.compute.manager [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Deallocating network for instance _deallocate_network /usr/lib/python2.7/site-packages/nova/compute/manager.py:1669
2019-03-29 10:39:53.192 18469 DEBUG nova.network.neutronv2.api [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] deallocate_for_instance() deallocate_for_instance /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1173
2019-03-29 10:39:53.256 18469 DEBUG neutronclient.v2_0.client [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-dfc05111-e280-4fdf-acb6-f681d6cbfac6 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:39:53.337 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 12e37154f163490abb5682d34bf912dd exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:53.368 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 12e37154f163490abb5682d34bf912dd __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:39:54.153 18469 DEBUG neutronclient.v2_0.client [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] DELETE call to neutron for http://172.30.126.56:9696/v2.0/ports/b3249515-3aab-439f-ba9c-bc498756871a.json used request id req-5333187d-855a-4cea-98e4-d9cfbc687a7d _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:39:54.154 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 45b855a635d64f90a50ae078b42c871c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:54.207 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 45b855a635d64f90a50ae078b42c871c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:39:54.208 18469 DEBUG nova.network.base_api [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:39:54.209 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: d9008ef364cf4b6eb082ec423bb3abd5 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:54.249 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: d9008ef364cf4b6eb082ec423bb3abd5 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:39:54.249 18469 INFO nova.compute.manager [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Took 1.06 seconds to deallocate network for instance.
2019-03-29 10:39:54.250 18469 DEBUG os_brick.utils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> get_connector_properties: call u"{'execute': None, 'my_ip': '172.30.126.58', 'enforce_multipath': True, 'host': 'com58', 'root_helper': 'sudo nova-rootwrap /etc/nova/rootwrap.conf', 'multipath': False}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:39:54.253 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'os_brick.privileged.rootwrap.execute_root', ('cat', '/etc/iscsi/initiatorname.iscsi'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:54.253 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): cat /etc/iscsi/initiatorname.iscsi out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:54.256 18469 DEBUG oslo.privsep.daemon [-] CMD "cat /etc/iscsi/initiatorname.iscsi" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:54.257 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, ('InitiatorName=iqn.1994-05.com.redhat:9affbb458449\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:39:54.257 18469 DEBUG os_brick.initiator.linuxfc [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:39:54.257 18469 DEBUG os_brick.initiator.linuxfc [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:39:54.258 18469 DEBUG os_brick.utils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== get_connector_properties: return (7ms) {'initiator': u'iqn.1994-05.com.redhat:9affbb458449', 'ip': u'172.30.126.58', 'platform': u'x86_64', 'host': u'com58', 'do_local_attach': False, 'os_type': u'linux2', 'multipath': False} trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:39:54.260 18469 DEBUG cinderclient.v2.client [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] REQ: curl -g -i -X POST http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}8909f64cb46a118d57e7cdb53d3762c4971c4edf" -d '{"os-terminate_connection": {"connector": {"platform": "x86_64", "host": "com58", "do_local_attach": false, "ip": "172.30.126.58", "os_type": "linux2", "multipath": false, "initiator": "iqn.1994-05.com.redhat:9affbb458449"}}}' _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:347
2019-03-29 10:39:54.479 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 05f9976bfc894c1a969eac4b4112aec9 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:39:54.481 18469 DEBUG nova.compute.manager [req-b090f470-92f4-4bfb-987f-41108a9b9472 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-vif-deleted-b3249515-3aab-439f-ba9c-bc498756871a external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:39:54.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_rescued_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:39:56.109 18469 DEBUG cinderclient.v2.client [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] RESP: [202] Content-Type: text/html; charset=UTF-8 Content-Length: 0 X-Openstack-Request-Id: req-ed47e5cb-5744-426d-bdb8-f0ddfaff1998 Date: Fri, 29 Mar 2019 02:39:56 GMT Connection: keep-alive 
RESP BODY: Omitted, Content-Type is set to text/html; charset=UTF-8. Only application/json responses have their bodies logged.
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:395
2019-03-29 10:39:56.110 18469 DEBUG cinderclient.v2.client [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] POST call to cinderv2 for http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action used request id req-ed47e5cb-5744-426d-bdb8-f0ddfaff1998 request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:640
2019-03-29 10:39:56.113 18469 DEBUG cinderclient.v2.client [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] REQ: curl -g -i -X GET http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e -H "User-Agent: python-cinderclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}8909f64cb46a118d57e7cdb53d3762c4971c4edf" _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:347
2019-03-29 10:39:56.202 18469 DEBUG cinderclient.v2.client [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] RESP: [200] X-Compute-Request-Id: req-cfefffa0-e53b-4b6d-a6a4-52565ab87182 Content-Type: application/json Content-Length: 1637 X-Openstack-Request-Id: req-cfefffa0-e53b-4b6d-a6a4-52565ab87182 Date: Fri, 29 Mar 2019 02:39:56 GMT Connection: keep-alive 
RESP BODY: {"volume": {"migration_status": null, "attachments": [{"server_id": "f5a19c94-1a45-4ea0-9386-77c10705c825", "attachment_id": "01cd6e94-3ba0-4d0f-8a92-1cccd1e17d82", "attached_at": "2019-03-29T02:02:40.000000", "host_name": null, "volume_id": "78a56ddc-ee21-4278-991e-17b30d68fa6e", "device": "/dev/vda", "id": "78a56ddc-ee21-4278-991e-17b30d68fa6e"}], "links": [{"href": "http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e", "rel": "self"}, {"href": "http://172.30.126.56:8776/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e", "rel": "bookmark"}], "availability_zone": "nova", "os-vol-host-attr:host": "ctl01@lvm#lvm", "encrypted": false, "updated_at": "2019-03-29T02:33:55.000000", "replication_status": null, "snapshot_id": null, "id": "78a56ddc-ee21-4278-991e-17b30d68fa6e", "size": 1, "user_id": "9e9e53917dda421083fa6af425c6bfbf", "os-vol-tenant-attr:tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "os-vol-mig-status-attr:migstat": null, "metadata": {"attached_mode": "rw"}, "status": "in-use", "volume_image_metadata": {"checksum": "ee1eca47dc88f4879d8a229cc70a07c6", "min_ram": "0", "disk_format": "qcow2", "image_name": "cirros", "image_id": "40f27f13-d552-4f7e-ae5d-2b85b126c85e", "architecture": "x86_64", "container_format": "bare", "min_disk": "0", "size": "13287936"}, "description": "", "multiattach": false, "source_volid": "d04e7667-4380-44f9-afb6-9a7327703c56", "consistencygroup_id": null, "os-vol-mig-status-attr:name_id": null, "name": "v2", "bootable": "true", "created_at": "2019-03-28T06:31:41.000000", "volume_type": "iscsi"}}
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:395
2019-03-29 10:39:56.203 18469 DEBUG cinderclient.v2.client [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to cinderv2 for http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e used request id req-cfefffa0-e53b-4b6d-a6a4-52565ab87182 request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:640
2019-03-29 10:39:56.204 18469 DEBUG cinderclient.v2.client [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] REQ: curl -g -i -X POST http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}8909f64cb46a118d57e7cdb53d3762c4971c4edf" -d '{"os-detach": {"attachment_id": null}}' _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:347
2019-03-29 10:39:58.505 18469 DEBUG cinderclient.v2.client [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] RESP: [202] Content-Type: text/html; charset=UTF-8 Content-Length: 0 X-Openstack-Request-Id: req-ba7f5150-2668-41fe-9ec4-41d98ccc8c32 Date: Fri, 29 Mar 2019 02:39:58 GMT Connection: keep-alive 
RESP BODY: Omitted, Content-Type is set to text/html; charset=UTF-8. Only application/json responses have their bodies logged.
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:395
2019-03-29 10:39:58.506 18469 DEBUG cinderclient.v2.client [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] POST call to cinderv2 for http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action used request id req-ba7f5150-2668-41fe-9ec4-41d98ccc8c32 request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:640
2019-03-29 10:39:58.507 18469 INFO nova.compute.manager [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Took 4.26 seconds to detach 1 volumes for instance.
2019-03-29 10:39:58.507 18469 WARNING nova.image.glance [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:39:58.512 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 5e316237946a4530993eac00240d098f exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:58.541 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 5e316237946a4530993eac00240d098f __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:39:58.542 18469 DEBUG nova.compute.manager [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] terminating bdm BlockDeviceMapping(boot_index=0,connection_info='{"driver_volume_type": "iscsi", "connector": {"platform": "x86_64", "host": "com58", "do_local_attach": false, "ip": "172.30.126.58", "os_type": "linux2", "multipath": false, "initiator": "iqn.1994-05.com.redhat:9affbb458449"}, "serial": "78a56ddc-ee21-4278-991e-17b30d68fa6e", "data": {"access_mode": "rw", "target_discovered": false, "encrypted": false, "qos_specs": null, "target_iqn": "iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e", "target_portal": "172.30.126.56:3260", "volume_id": "78a56ddc-ee21-4278-991e-17b30d68fa6e", "target_lun": 0, "device_path": "/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0", "auth_password": "***", "auth_username": "PutS9jPtTsLadXTr42qr", "auth_method": "CHAP"}}',created_at=2019-03-29T02:02:34Z,delete_on_termination=False,deleted=False,deleted_at=None,destination_type='volume',device_name='/dev/vda',device_type='disk',disk_bus='virtio',guest_format=None,id=24,image_id=None,instance=<?>,instance_uuid=f5a19c94-1a45-4ea0-9386-77c10705c825,no_device=False,snapshot_id=None,source_type='volume',tag=None,updated_at=2019-03-29T02:33:59Z,volume_id='78a56ddc-ee21-4278-991e-17b30d68fa6e',volume_size=1) _cleanup_volumes /usr/lib/python2.7/site-packages/nova/compute/manager.py:2319
2019-03-29 10:39:58.548 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 885f339c26354314b2416810eab0728b exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:58.619 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 885f339c26354314b2416810eab0728b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:39:58.623 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 19289da3a558464a9e12a21ec80fef32 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:58.743 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 19289da3a558464a9e12a21ec80fef32 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:39:58.746 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 4638ca9db9fa45f1a1d3d0271893d705 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:58.800 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4638ca9db9fa45f1a1d3d0271893d705 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:39:58.801 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 129a55aec29444ac8ae503a787c3c7f2 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:58.809 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 129a55aec29444ac8ae503a787c3c7f2 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:39:58.810 18469 DEBUG oslo_concurrency.lockutils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker.update_usage" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:39:58.850 18469 INFO nova.scheduler.client.report [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Deleted allocation for instance f5a19c94-1a45-4ea0-9386-77c10705c825
2019-03-29 10:39:58.857 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 75c23d9450db42c281badf747269505c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:58.909 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 75c23d9450db42c281badf747269505c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:39:58.911 18469 DEBUG nova.scheduler.client.report [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:39:58.937 18469 DEBUG oslo_concurrency.lockutils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" released by "nova.compute.resource_tracker.update_usage" :: held 0.127s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:39:58.937 18469 WARNING nova.image.glance [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:39:58.940 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CAST unique_id: 3efb6733a1ea457f91704eb55cdfbf3f exchange 'nova' topic 'consoleauth' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:58.942 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CAST unique_id: c23241b76f1449baa5c210cffe8692df FANOUT topic 'scheduler' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:539
2019-03-29 10:39:58.945 18469 DEBUG oslo_concurrency.lockutils [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825" released by "nova.compute.manager.do_terminate_instance" :: held 8.265s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:39:58.946 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-4c66ba5a-f40b-47f8-8e45-31e78b28befa 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: c224c2cfd64341a9bb888670ad5d317b exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:39:58.971 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: c224c2cfd64341a9bb888670ad5d317b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:40:03.341 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 9a6f677a42e6454aaaaecdfac7a65aef exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:40:03.394 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 9a6f677a42e6454aaaaecdfac7a65aef __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:40:05.901 18469 DEBUG nova.virt.driver [-] Emitting event <LifecycleEvent: 1553827190.9, f5a19c94-1a45-4ea0-9386-77c10705c825 => Stopped> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:40:05.902 18469 INFO nova.compute.manager [-] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Stopped (Lifecycle Event)
2019-03-29 10:40:05.904 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-3b4fafc8-ba87-4c3a-a638-ced1083ae2e3 - - - - -] CALL msg_id: 507cf0a52b1541c7b3feefc62d54f04a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:40:05.953 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 507cf0a52b1541c7b3feefc62d54f04a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:40:05.955 18469 DEBUG nova.compute.manager [req-3b4fafc8-ba87-4c3a-a638-ced1083ae2e3 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
