2019-03-29 10:33:03.349 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: a6240de9eebb4ebf93cbeffd3cc62dba exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:03.404 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a6240de9eebb4ebf93cbeffd3cc62dba __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:07.701 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._reclaim_queued_deletes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:33:07.702 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CONF.reclaim_instance_interval <= 0, skipping... _reclaim_queued_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6556
2019-03-29 10:33:10.298 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: abee96446f4043ee9dec0fcbbaccddec __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:33:10.301 18469 DEBUG oslo_concurrency.lockutils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825" acquired by "nova.compute.manager.do_shelve_offload_instance" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:33:10.302 18469 INFO nova.compute.manager [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Shelve offloading
2019-03-29 10:33:10.302 18469 WARNING nova.image.glance [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:33:10.302 18469 DEBUG nova.objects.instance [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'flavor' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:33:10.303 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: eba9bd9c57cc4d16ad081fabfeea4edf exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:10.360 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: eba9bd9c57cc4d16ad081fabfeea4edf __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:10.367 18469 DEBUG nova.virt.libvirt.driver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Shutting down instance from state 1 _clean_shutdown /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:2520
2019-03-29 10:33:13.347 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: c3e9cfb2b8a7494c8c91a909c806f0ff exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:13.379 18469 INFO nova.virt.libvirt.driver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance shutdown successfully after 3 seconds.
2019-03-29 10:33:13.394 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: c3e9cfb2b8a7494c8c91a909c806f0ff __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:13.591 18469 INFO nova.virt.libvirt.driver [-] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance destroyed successfully.
2019-03-29 10:33:13.592 18469 DEBUG nova.compute.manager [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:33:13.594 18469 DEBUG oslo_concurrency.lockutils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Acquired semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:33:13.594 18469 DEBUG nova.network.neutronv2.api [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:33:13.596 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 0f2cd7d24cd24009bf11a5c9bd12e728 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:13.611 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 0f2cd7d24cd24009bf11a5c9bd12e728 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:13.853 18469 DEBUG neutronclient.v2_0.client [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-dc507331-c130-4862-bbd3-a0e966cec4b8 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:13.970 18469 DEBUG neutronclient.v2_0.client [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-45739a96-828e-42db-b1e0-02abc9e5905d _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:13.995 18469 DEBUG neutronclient.v2_0.client [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.11&port_id=b3249515-3aab-439f-ba9c-bc498756871a used request id req-d4d60c9b-36ac-44a3-b469-be190a802200 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:14.053 18469 DEBUG neutronclient.v2_0.client [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-c473cf28-ce4d-4ed9-9063-8eb8e8c2588d _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:14.103 18469 DEBUG neutronclient.v2_0.client [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-12a64bea-61f7-4b60-b431-c15c95e1da68 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:14.104 18469 DEBUG nova.network.base_api [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": true, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:33:14.105 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 6b6e33ab567e4157af7937650fa25e4f exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:14.117 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 6b6e33ab567e4157af7937650fa25e4f __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:14.119 18469 DEBUG oslo_concurrency.lockutils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Releasing semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:33:14.120 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: c8df1c776e554d4b99c5c5adb20e2f96 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:14.130 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: c8df1c776e554d4b99c5c5adb20e2f96 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:14.136 18469 INFO nova.virt.libvirt.driver [-] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance destroyed successfully.
2019-03-29 10:33:14.137 18469 DEBUG nova.virt.libvirt.vif [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] vif_type=ovs instance=Instance(access_ip_v4=None,access_ip_v6=None,architecture='x86_64',auto_disk_config=True,availability_zone='nova',cell_name=None,cleaned=True,config_drive='True',created_at=2019-03-29T02:02:33Z,default_ephemeral_device=None,default_swap_device=None,deleted=False,deleted_at=None,device_metadata=<?>,disable_terminate=False,display_description='vm001',display_name='vm001',ec2_ids=<?>,ephemeral_gb=0,ephemeral_key_uuid=None,fault=<?>,flavor=Flavor(1),host='com58',hostname='vm001',id=24,image_ref='',info_cache=InstanceInfoCache,instance_type_id=1,kernel_id='',key_data=None,key_name=None,keypairs=<?>,launch_index=0,launched_at=2019-03-29T02:12:27Z,launched_on='com58',locked=False,locked_by=None,memory_mb=512,metadata={},migration_context=<?>,new_flavor=None,node='com58',numa_topology=<?>,old_flavor=None,os_type=None,pci_devices=<?>,pci_requests=<?>,power_state=1,progress=0,project_id='d4bbd972ca1b463ba028ccd1df983917',ramdisk_id='',reservation_id='r-x56iqcqr',root_device_name='/dev/vda',root_gb=1,security_groups=SecurityGroupList,services=<?>,shutdown_terminate=False,system_metadata={boot_roles='admin',clean_attempts='1',image_architecture='x86_64',image_base_image_ref='',image_min_disk='1',image_min_ram='0'},tags=<?>,task_state='shelving',terminated_at=None,updated_at=2019-03-29T02:32:00Z,user_data=None,user_id='9e9e53917dda421083fa6af425c6bfbf',uuid=f5a19c94-1a45-4ea0-9386-77c10705c825,vcpu_model=<?>,vcpus=1,vm_mode=None,vm_state='active') vif={"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": true, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} unplug /usr/lib/python2.7/site-packages/nova/virt/libvirt/vif.py:966
2019-03-29 10:33:14.138 18469 DEBUG nova.network.os_vif_util [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converting VIF {"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": true, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:413
2019-03-29 10:33:14.139 18469 DEBUG nova.network.os_vif_util [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converted object VIFBridge(active=True,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:425
2019-03-29 10:33:14.140 18469 DEBUG os_vif [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Unplugging vif VIFBridge(active=True,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') unplug /usr/lib/python2.7/site-packages/os_vif/__init__.py:112
2019-03-29 10:33:14.141 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285616]: (3, 'vif_plug_ovs.linux_net.delete_bridge', (u'qbrb3249515-3a', 'qvbb3249515-3a'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.141 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl delif qbrb3249515-3a qvbb3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.157 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl delif qbrb3249515-3a qvbb3249515-3a" returned: 0 in 0.015s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.157 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qbrb3249515-3a down out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.164 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qbrb3249515-3a down" returned: 0 in 0.007s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.165 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl delbr qbrb3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.178 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl delbr qbrb3249515-3a" returned: 0 in 0.014s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.179 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285616]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.181 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285616]: (3, 'vif_plug_ovs.linux_net.delete_ovs_vif_port', (u'br-int', 'qvob3249515-3a'), {'timeout': 120}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.182 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ovs-vsctl --timeout=120 -- --if-exists del-port br-int qvob3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.198 18469 DEBUG oslo.privsep.daemon [-] CMD "ovs-vsctl --timeout=120 -- --if-exists del-port br-int qvob3249515-3a" returned: 0 in 0.017s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.198 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link delete qvob3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.214 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link delete qvob3249515-3a" returned: 0 in 0.017s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.215 18469 DEBUG oslo.privsep.daemon [-] Net device removed: 'qvob3249515-3a' out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.215 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285616]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.215 18469 INFO os_vif [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Successfully unplugged vif VIFBridge(active=True,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a')
2019-03-29 10:33:14.216 18469 DEBUG nova.virt.libvirt.volume.iscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] calling os-brick to detach iSCSI Volume disconnect_volume /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/iscsi.py:72
2019-03-29 10:33:14.217 18469 DEBUG os_brick.initiator.connectors.iscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> disconnect_volume: call u"{'args': (<os_brick.initiator.connectors.iscsi.ISCSIConnector object at 0x5ae9b50>, {u'device_path': u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0', u'target_discovered': False, u'encrypted': False, u'qos_specs': None, u'target_iqn': u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_portal': u'172.30.126.56:3260', u'volume_id': u'78a56ddc-ee21-4278-991e-17b30d68fa6e', u'auth_password': u'***', u'target_lun': 0, u'access_mode': u'rw', u'auth_username': u'PutS9jPtTsLadXTr42qr', u'auth_method': u'CHAP'}, None), 'kwargs': {}}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:33:14.217 18469 DEBUG oslo_concurrency.lockutils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "connect_volume" acquired by "os_brick.initiator.connectors.iscsi.disconnect_volume" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:33:14.218 18469 DEBUG os_brick.initiator.linuxscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Flushing IO for device /dev/sdb flush_device_io /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:146
2019-03-29 10:33:14.220 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285616]: (3, 'os_brick.privileged.rootwrap.execute_root', ('blockdev', '--flushbufs', u'/dev/sdb'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.220 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): blockdev --flushbufs /dev/sdb out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.224 18469 DEBUG oslo.privsep.daemon [-] CMD "blockdev --flushbufs /dev/sdb" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.224 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285616]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.224 18469 DEBUG os_brick.initiator.linuxscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Remove SCSI device /dev/sdb with /sys/block/sdb/device/delete remove_scsi_device /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:69
2019-03-29 10:33:14.226 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285616]: (3, 'os_brick.privileged.rootwrap.execute_root', ('tee', '-a', u'/sys/block/sdb/device/delete'), {'process_input': '1'}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.227 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): tee -a /sys/block/sdb/device/delete out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.230 18469 DEBUG oslo.privsep.daemon [-] CMD "tee -a /sys/block/sdb/device/delete" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.230 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285616]: (4, ('1', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:14.230 18469 DEBUG os_brick.initiator.linuxscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Checking to see if SCSI volume /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 has been removed. wait_for_volume_removal /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:77
2019-03-29 10:33:14.232 18469 DEBUG os_brick.initiator.linuxscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 still exists. wait_for_volume_removal /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:79
2019-03-29 10:33:14.233 18469 DEBUG os_brick.utils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Failed attempt 1 _print_stop /usr/lib/python2.7/site-packages/os_brick/utils.py:45
2019-03-29 10:33:14.233 18469 DEBUG os_brick.utils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Have been at this for 0.002 seconds _print_stop /usr/lib/python2.7/site-packages/os_brick/utils.py:47
2019-03-29 10:33:14.233 18469 DEBUG os_brick.utils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Sleeping for 2 seconds _backoff_sleep /usr/lib/python2.7/site-packages/os_brick/utils.py:40
2019-03-29 10:33:14.833 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 9477642a31bc41d4839db341a1316bbd __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:33:14.835 18469 DEBUG nova.compute.manager [req-9552e303-5436-47b4-8585-4130c8de6160 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-vif-unplugged-b3249515-3aab-439f-ba9c-bc498756871a external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:33:14.836 18469 DEBUG oslo_concurrency.lockutils [req-9552e303-5436-47b4-8585-4130c8de6160 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:33:14.836 18469 DEBUG nova.compute.manager [req-9552e303-5436-47b4-8585-4130c8de6160 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:350
2019-03-29 10:33:14.837 18469 DEBUG oslo_concurrency.lockutils [req-9552e303-5436-47b4-8585-4130c8de6160 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._pop_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:33:14.837 18469 DEBUG nova.compute.manager [req-9552e303-5436-47b4-8585-4130c8de6160 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] No waiting events found dispatching network-vif-unplugged-b3249515-3aab-439f-ba9c-bc498756871a pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:366
2019-03-29 10:33:14.837 18469 WARNING nova.compute.manager [req-9552e303-5436-47b4-8585-4130c8de6160 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received unexpected event network-vif-unplugged-b3249515-3aab-439f-ba9c-bc498756871a for instance
2019-03-29 10:33:16.234 18469 DEBUG os_brick.initiator.linuxscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Checking to see if SCSI volume /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 has been removed. wait_for_volume_removal /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:77
2019-03-29 10:33:16.235 18469 DEBUG os_brick.initiator.linuxscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] SCSI volume /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 has been removed. wait_for_volume_removal /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:83
2019-03-29 10:33:16.236 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285616]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.startup', '-v', 'manual'), {'attempts': 1, 'check_exit_code': (0, 21, 255), 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.237 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.startup -v manual out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.247 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.startup -v manual" returned: 0 in 0.011s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.247 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285616]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.248 18469 DEBUG os_brick.initiator.connectors.iscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.startup', '-v', 'manual'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:33:16.249 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285616]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--logout'), {'attempts': 1, 'check_exit_code': (0, 21, 255), 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.250 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --logout out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.262 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --logout" returned: 0 in 0.013s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.263 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285616]: (4, ('Logging out of session [sid: 9, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260]\nLogout of [sid: 9, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] successful.\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.263 18469 DEBUG os_brick.initiator.connectors.iscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--logout',): stdout=Logging out of session [sid: 9, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260]
Logout of [sid: 9, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] successful.
 stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:33:16.264 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285616]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'delete'), {'attempts': 5, 'check_exit_code': (0, 21, 255), 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.264 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op delete out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.270 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op delete" returned: 0 in 0.006s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.271 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285616]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.271 18469 DEBUG os_brick.initiator.connectors.iscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'delete'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:33:16.271 18469 DEBUG oslo_concurrency.lockutils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "connect_volume" released by "os_brick.initiator.connectors.iscsi.disconnect_volume" :: held 2.054s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:33:16.272 18469 DEBUG os_brick.initiator.connectors.iscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== disconnect_volume: return (2054ms) None trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:33:16.272 18469 DEBUG nova.virt.libvirt.volume.iscsi [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Disconnected iSCSI Volume vda disconnect_volume /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/iscsi.py:78
2019-03-29 10:33:16.273 18469 DEBUG oslo_concurrency.processutils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): mv /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825 /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_del execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:33:16.284 18469 DEBUG oslo_concurrency.processutils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "mv /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825 /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_del" returned: 0 in 0.011s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:33:16.285 18469 INFO nova.virt.libvirt.driver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Deleting instance files /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_del
2019-03-29 10:33:16.286 18469 INFO nova.virt.libvirt.driver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Deletion of /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_del complete
2019-03-29 10:33:16.289 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 0464b26f09f54b498bc992e034cdabdd exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:16.572 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 0464b26f09f54b498bc992e034cdabdd __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:16.580 18469 DEBUG os_brick.utils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> get_connector_properties: call u"{'execute': None, 'my_ip': '172.30.126.58', 'enforce_multipath': True, 'host': 'com58', 'root_helper': 'sudo nova-rootwrap /etc/nova/rootwrap.conf', 'multipath': False}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:33:16.582 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285616]: (3, 'os_brick.privileged.rootwrap.execute_root', ('cat', '/etc/iscsi/initiatorname.iscsi'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.582 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): cat /etc/iscsi/initiatorname.iscsi out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.586 18469 DEBUG oslo.privsep.daemon [-] CMD "cat /etc/iscsi/initiatorname.iscsi" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.586 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285616]: (4, ('InitiatorName=iqn.1994-05.com.redhat:9affbb458449\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:16.587 18469 DEBUG os_brick.initiator.linuxfc [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:33:16.587 18469 DEBUG os_brick.initiator.linuxfc [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:33:16.588 18469 DEBUG os_brick.utils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== get_connector_properties: return (6ms) {'initiator': u'iqn.1994-05.com.redhat:9affbb458449', 'ip': u'172.30.126.58', 'platform': u'x86_64', 'host': u'com58', 'do_local_attach': False, 'os_type': u'linux2', 'multipath': False} trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:33:16.590 18469 DEBUG cinderclient.v2.client [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] REQ: curl -g -i -X POST http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}8909f64cb46a118d57e7cdb53d3762c4971c4edf" -d '{"os-terminate_connection": {"connector": {"platform": "x86_64", "host": "com58", "do_local_attach": false, "ip": "172.30.126.58", "os_type": "linux2", "multipath": false, "initiator": "iqn.1994-05.com.redhat:9affbb458449"}}}' _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:347
2019-03-29 10:33:16.701 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_rebooting_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:33:17.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._heal_instance_info_cache run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:33:17.700 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Starting heal instance info cache _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5884
2019-03-29 10:33:17.701 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Rebuilding the list of instances to heal _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5888
2019-03-29 10:33:17.703 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: b22a818b79b840b6a254b150c2c7b08c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:17.734 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b22a818b79b840b6a254b150c2c7b08c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:17.737 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Acquired semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:33:17.738 18469 DEBUG nova.network.neutronv2.api [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:33:17.738 18469 DEBUG nova.objects.instance [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lazy-loading 'info_cache' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:33:17.740 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 1b7463f082fa40eb8f8157a46610b07a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:17.785 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 1b7463f082fa40eb8f8157a46610b07a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:17.789 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 58dc01febd6a4100852f429c5966bae4 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:17.806 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 58dc01febd6a4100852f429c5966bae4 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:17.868 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-7fb03dc5-09e7-4732-bfc9-2fb5b763d3bb _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:17.976 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-36dd1587-7e34-44cf-a99e-e05668215af9 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:17.998 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.11&port_id=b3249515-3aab-439f-ba9c-bc498756871a used request id req-3e8762ca-3b36-43aa-a886-ee92624863c9 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:18.060 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-cae28a91-cb45-48dd-be1c-818dd0b4b93a _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:18.107 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-5e8843bf-c298-45c1-a559-a73e531f305c _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:18.108 18469 DEBUG nova.network.base_api [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:33:18.110 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: bdf8baae6b994ff19be8b15ac740fb65 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:18.150 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: bdf8baae6b994ff19be8b15ac740fb65 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:18.151 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Releasing semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:33:18.152 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updated the network info_cache for instance _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5946
2019-03-29 10:33:18.308 18469 DEBUG cinderclient.v2.client [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] RESP: [202] Content-Type: text/html; charset=UTF-8 Content-Length: 0 X-Openstack-Request-Id: req-0c05098e-ddda-4ed1-a2ed-3b557f8bbb22 Date: Fri, 29 Mar 2019 02:33:18 GMT Connection: keep-alive 
RESP BODY: Omitted, Content-Type is set to text/html; charset=UTF-8. Only application/json responses have their bodies logged.
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:395
2019-03-29 10:33:18.308 18469 DEBUG cinderclient.v2.client [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] POST call to cinderv2 for http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action used request id req-0c05098e-ddda-4ed1-a2ed-3b557f8bbb22 request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:640
2019-03-29 10:33:18.314 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 4bb56b83817447dabfd7ec49e41ea168 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:18.409 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4bb56b83817447dabfd7ec49e41ea168 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:18.411 18469 DEBUG oslo_concurrency.lockutils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker.update_usage" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:33:18.470 18469 INFO nova.scheduler.client.report [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Deleted allocation for instance f5a19c94-1a45-4ea0-9386-77c10705c825
2019-03-29 10:33:18.471 18469 DEBUG nova.objects.instance [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'numa_topology' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:33:18.473 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 9d217847335f4c619945579a9f073206 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:18.493 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 9d217847335f4c619945579a9f073206 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:18.499 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: a01ea61c3aac4dc5a98062c20575d96b exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:18.535 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a01ea61c3aac4dc5a98062c20575d96b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:18.537 18469 DEBUG nova.scheduler.client.report [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:33:18.579 18469 DEBUG oslo_concurrency.lockutils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" released by "nova.compute.resource_tracker.update_usage" :: held 0.167s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:33:18.584 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: d821fda1a8ab4116ae96affaf2e3082b exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:18.657 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: d821fda1a8ab4116ae96affaf2e3082b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:18.661 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CAST unique_id: 51af2cfd19c04e07a389199160f7bb35 FANOUT topic 'scheduler' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:539
2019-03-29 10:33:18.664 18469 WARNING nova.image.glance [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:33:18.667 18469 DEBUG oslo_concurrency.lockutils [req-5cdeb439-06f9-4e8e-ba85-6e397ddd75b9 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825" released by "nova.compute.manager.do_shelve_offload_instance" :: held 8.366s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:33:23.348 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 82d8564bff22425982237efb43905bbf exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:23.383 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 82d8564bff22425982237efb43905bbf __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:25.154 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._instance_usage_audit run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:33:26.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_unconfirmed_resizes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:33:28.590 18469 DEBUG nova.virt.driver [-] Emitting event <LifecycleEvent: 1553826793.59, f5a19c94-1a45-4ea0-9386-77c10705c825 => Stopped> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:33:28.591 18469 INFO nova.compute.manager [-] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Stopped (Lifecycle Event)
2019-03-29 10:33:28.593 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-3c2053b9-cbce-4399-abe8-771e0dc0e384 - - - - -] CALL msg_id: 70e5f2769297465db5863cfe9d2e6794 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:28.641 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 70e5f2769297465db5863cfe9d2e6794 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:28.643 18469 DEBUG nova.compute.manager [req-3c2053b9-cbce-4399-abe8-771e0dc0e384 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:33:28.697 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._check_instance_build_time run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:33:32.701 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_volume_usage run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:33:33.345 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 9954012dcb1e41b9bac83f783c21e946 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:33.382 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 9954012dcb1e41b9bac83f783c21e946 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:33.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager.update_available_resource run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:33:33.701 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 92acd303ebbc4f8ba04220523bbd90be exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:33.715 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 92acd303ebbc4f8ba04220523bbd90be __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:33.721 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Auditing locally available compute resources for com58 (node: com58) update_available_resource /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:534
2019-03-29 10:33:33.819 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Hypervisor: free VCPUs: 2 _report_hypervisor_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:655
2019-03-29 10:33:33.820 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Hypervisor/Node resource view: name=com58 free_ram=7094MB free_disk=45GB free_vcpus=2 pci_devices=[{"dev_id": "pci_0000_00_00_0", "product_id": "7190", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7190", "address": "0000:00:00.0"}, {"dev_id": "pci_0000_00_01_0", "product_id": "7191", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7191", "address": "0000:00:01.0"}, {"dev_id": "pci_0000_00_07_0", "product_id": "7110", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7110", "address": "0000:00:07.0"}, {"dev_id": "pci_0000_00_07_1", "product_id": "7111", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7111", "address": "0000:00:07.1"}, {"dev_id": "pci_0000_00_07_3", "product_id": "7113", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7113", "address": "0000:00:07.3"}, {"dev_id": "pci_0000_00_07_7", "product_id": "0740", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0740", "address": "0000:00:07.7"}, {"dev_id": "pci_0000_00_0f_0", "product_id": "0405", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0405", "address": "0000:00:0f.0"}, {"dev_id": "pci_0000_00_11_0", "product_id": "0790", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0790", "address": "0000:00:11.0"}, {"dev_id": "pci_0000_00_15_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.0"}, {"dev_id": "pci_0000_03_00_0", "product_id": "07c0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07c0", "address": "0000:03:00.0"}, {"dev_id": "pci_0000_00_15_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.1"}, {"dev_id": "pci_0000_00_15_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.2"}, {"dev_id": "pci_0000_00_15_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.3"}, {"dev_id": "pci_0000_00_15_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.4"}, {"dev_id": "pci_0000_00_15_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.5"}, {"dev_id": "pci_0000_00_15_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.6"}, {"dev_id": "pci_0000_00_15_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.7"}, {"dev_id": "pci_0000_00_16_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.0"}, {"dev_id": "pci_0000_0b_00_0", "product_id": "07b0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07b0", "address": "0000:0b:00.0"}, {"dev_id": "pci_0000_00_16_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.1"}, {"dev_id": "pci_0000_00_16_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.2"}, {"dev_id": "pci_0000_00_16_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.3"}, {"dev_id": "pci_0000_00_16_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.4"}, {"dev_id": "pci_0000_00_16_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.5"}, {"dev_id": "pci_0000_00_16_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.6"}, {"dev_id": "pci_0000_00_16_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.7"}, {"dev_id": "pci_0000_00_17_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.0"}, {"dev_id": "pci_0000_13_00_0", "product_id": "07b0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07b0", "address": "0000:13:00.0"}, {"dev_id": "pci_0000_00_17_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.1"}, {"dev_id": "pci_0000_00_17_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.2"}, {"dev_id": "pci_0000_00_17_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.3"}, {"dev_id": "pci_0000_00_17_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.4"}, {"dev_id": "pci_0000_00_17_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.5"}, {"dev_id": "pci_0000_00_17_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.6"}, {"dev_id": "pci_0000_00_17_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.7"}, {"dev_id": "pci_0000_00_18_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.0"}, {"dev_id": "pci_0000_00_18_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.1"}, {"dev_id": "pci_0000_00_18_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.2"}, {"dev_id": "pci_0000_00_18_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.3"}, {"dev_id": "pci_0000_00_18_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.4"}, {"dev_id": "pci_0000_00_18_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.5"}, {"dev_id": "pci_0000_00_18_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.6"}, {"dev_id": "pci_0000_00_18_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.7"}] _report_hypervisor_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:672
2019-03-29 10:33:33.820 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker._update_available_resource" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:33:33.822 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: b42105a22cbd4b4a97c2bc43b67491ff exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:33.864 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b42105a22cbd4b4a97c2bc43b67491ff __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:33.865 18469 DEBUG nova.scheduler.client.report [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:33:33.895 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: f2e798bc762948c49c703d155e748360 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:33.911 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: f2e798bc762948c49c703d155e748360 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:33.926 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 4713a57618bb478381439b13773c8f5b exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:33.957 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4713a57618bb478381439b13773c8f5b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:33.958 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Total usable vcpus: 2, total allocated vcpus: 0 _report_final_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:688
2019-03-29 10:33:33.958 18469 INFO nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Final resource view: name=com58 phys_ram=8191MB used_ram=512MB phys_disk=47GB used_disk=0GB total_vcpus=2 used_vcpus=0 pci_stats=[]
2019-03-29 10:33:33.962 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: e066e76c8efe4b459094d45c022fa299 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:33.989 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: e066e76c8efe4b459094d45c022fa299 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:33.989 18469 DEBUG nova.scheduler.client.report [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:33:34.013 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Compute_service record updated for com58:com58 _update_available_resource /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:626
2019-03-29 10:33:34.014 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lock "compute_resources" released by "nova.compute.resource_tracker._update_available_resource" :: held 0.193s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282


















2019-03-29 10:33:43.347 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 57b907805a8f431499544725bc12a86e exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:43.378 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 57b907805a8f431499544725bc12a86e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:45.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_rescued_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:33:52.448 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 11361ffb20a44262aa076fa6a85a859d __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:33:52.452 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 2ef0345702db47579345ea64937daf54 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:52.491 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 2ef0345702db47579345ea64937daf54 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:52.492 18469 DEBUG oslo_concurrency.lockutils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825" acquired by "nova.compute.manager.do_unshelve_instance" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:33:52.493 18469 INFO nova.compute.manager [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Unshelving
2019-03-29 10:33:52.493 18469 WARNING nova.image.glance [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:33:52.494 18469 DEBUG nova.objects.instance [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'flavor' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:33:52.495 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: a64e5ee60aa34dd0bd81e9170cfd3ea3 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:52.541 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a64e5ee60aa34dd0bd81e9170cfd3ea3 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:52.548 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 408503a8678e4ad490742575338211cf exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:52.686 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 408503a8678e4ad490742575338211cf __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:52.688 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: b0bee837540544cd911c8ad835b8448a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:52.701 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b0bee837540544cd911c8ad835b8448a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:52.703 18469 INFO nova.virt.block_device [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Booting with blank volume at /dev/vda
2019-03-29 10:33:52.706 18469 DEBUG cinderclient.v2.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] REQ: curl -g -i -X GET http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e -H "User-Agent: python-cinderclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}565b95e1b59c00569eacc9f28a9f5472a35f8add" _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:347
2019-03-29 10:33:52.968 18469 DEBUG cinderclient.v2.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] RESP: [200] X-Compute-Request-Id: req-d20f9759-adbc-41c8-9e8d-f190e601847c Content-Type: application/json Content-Length: 1637 X-Openstack-Request-Id: req-d20f9759-adbc-41c8-9e8d-f190e601847c Date: Fri, 29 Mar 2019 02:33:53 GMT Connection: keep-alive 
RESP BODY: {"volume": {"migration_status": null, "attachments": [{"server_id": "f5a19c94-1a45-4ea0-9386-77c10705c825", "attachment_id": "01cd6e94-3ba0-4d0f-8a92-1cccd1e17d82", "attached_at": "2019-03-29T02:02:40.000000", "host_name": null, "volume_id": "78a56ddc-ee21-4278-991e-17b30d68fa6e", "device": "/dev/vda", "id": "78a56ddc-ee21-4278-991e-17b30d68fa6e"}], "links": [{"href": "http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e", "rel": "self"}, {"href": "http://172.30.126.56:8776/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e", "rel": "bookmark"}], "availability_zone": "nova", "os-vol-host-attr:host": "ctl01@lvm#lvm", "encrypted": false, "updated_at": "2019-03-29T02:12:26.000000", "replication_status": null, "snapshot_id": null, "id": "78a56ddc-ee21-4278-991e-17b30d68fa6e", "size": 1, "user_id": "9e9e53917dda421083fa6af425c6bfbf", "os-vol-tenant-attr:tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "os-vol-mig-status-attr:migstat": null, "metadata": {"attached_mode": "rw"}, "status": "in-use", "volume_image_metadata": {"checksum": "ee1eca47dc88f4879d8a229cc70a07c6", "min_ram": "0", "disk_format": "qcow2", "image_name": "cirros", "image_id": "40f27f13-d552-4f7e-ae5d-2b85b126c85e", "architecture": "x86_64", "container_format": "bare", "min_disk": "0", "size": "13287936"}, "description": "", "multiattach": false, "source_volid": "d04e7667-4380-44f9-afb6-9a7327703c56", "consistencygroup_id": null, "os-vol-mig-status-attr:name_id": null, "name": "v2", "bootable": "true", "created_at": "2019-03-28T06:31:41.000000", "volume_type": "iscsi"}}
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:395
2019-03-29 10:33:52.969 18469 DEBUG cinderclient.v2.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to cinderv2 for http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e used request id req-d20f9759-adbc-41c8-9e8d-f190e601847c request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:640
2019-03-29 10:33:52.970 18469 DEBUG os_brick.utils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> get_connector_properties: call u"{'execute': None, 'my_ip': '172.30.126.58', 'enforce_multipath': True, 'host': 'com58', 'root_helper': 'sudo nova-rootwrap /etc/nova/rootwrap.conf', 'multipath': False}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:33:52.974 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'os_brick.privileged.rootwrap.execute_root', ('cat', '/etc/iscsi/initiatorname.iscsi'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:52.974 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): cat /etc/iscsi/initiatorname.iscsi out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:52.978 18469 DEBUG oslo.privsep.daemon [-] CMD "cat /etc/iscsi/initiatorname.iscsi" returned: 0 in 0.006s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:52.979 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, ('InitiatorName=iqn.1994-05.com.redhat:9affbb458449\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:52.979 18469 DEBUG os_brick.initiator.linuxfc [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:33:52.980 18469 DEBUG os_brick.initiator.linuxfc [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:33:52.980 18469 DEBUG os_brick.utils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== get_connector_properties: return (9ms) {'initiator': u'iqn.1994-05.com.redhat:9affbb458449', 'ip': u'172.30.126.58', 'platform': u'x86_64', 'host': u'com58', 'do_local_attach': False, 'os_type': u'linux2', 'multipath': False} trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:33:52.982 18469 DEBUG cinderclient.v2.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] REQ: curl -g -i -X POST http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}565b95e1b59c00569eacc9f28a9f5472a35f8add" -d '{"os-initialize_connection": {"connector": {"platform": "x86_64", "host": "com58", "do_local_attach": false, "ip": "172.30.126.58", "os_type": "linux2", "multipath": false, "initiator": "iqn.1994-05.com.redhat:9affbb458449"}}}' _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:347
2019-03-29 10:33:53.351 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: c7fbd98dc97f4e14892d742461027bae exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:53.395 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: c7fbd98dc97f4e14892d742461027bae __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:56.665 18469 DEBUG cinderclient.v2.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] RESP: [200] X-Compute-Request-Id: req-d9879050-52e2-4897-8021-dc2da1b82a7f Content-Type: application/json Content-Length: 447 X-Openstack-Request-Id: req-d9879050-52e2-4897-8021-dc2da1b82a7f Date: Fri, 29 Mar 2019 02:33:57 GMT Connection: keep-alive 
RESP BODY: {"connection_info": {"driver_volume_type": "iscsi", "data": {"auth_password": "TPnqk7LML2MKpPv4", "target_discovered": false, "encrypted": false, "qos_specs": null, "target_iqn": "iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e", "target_portal": "172.30.126.56:3260", "volume_id": "78a56ddc-ee21-4278-991e-17b30d68fa6e", "target_lun": 0, "access_mode": "rw", "auth_username": "PutS9jPtTsLadXTr42qr", "auth_method": "CHAP"}}}
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:395
2019-03-29 10:33:56.666 18469 DEBUG cinderclient.v2.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] POST call to cinderv2 for http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action used request id req-d9879050-52e2-4897-8021-dc2da1b82a7f request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:640
2019-03-29 10:33:56.669 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 039a2dcee2e244b689e109857f4ce2d1 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:56.743 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 039a2dcee2e244b689e109857f4ce2d1 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:56.758 18469 DEBUG neutronclient.v2_0.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/extensions.json used request id req-c92e78cf-7222-4b7f-87dd-da34116681dc _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:56.820 18469 DEBUG neutronclient.v2_0.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-7ef240bf-d1a7-4308-9289-ec837ad42435 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:56.821 18469 DEBUG oslo_concurrency.lockutils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Acquired semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:33:56.822 18469 DEBUG nova.network.neutronv2.api [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:33:56.823 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 916a498448c340c9ac8542ce2e62af2a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:56.832 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 916a498448c340c9ac8542ce2e62af2a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:56.894 18469 DEBUG neutronclient.v2_0.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-358eb8d0-5175-49bd-91e0-4b0a083f37b9 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:57.000 18469 DEBUG neutronclient.v2_0.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-eb653f3a-6341-4973-982a-e00057a6ece6 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:57.023 18469 DEBUG neutronclient.v2_0.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.11&port_id=b3249515-3aab-439f-ba9c-bc498756871a used request id req-02a98187-3cf3-4167-9c6c-32dc3f764be7 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:57.087 18469 DEBUG neutronclient.v2_0.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-17f32f5b-05f5-44eb-bd68-558d165ed821 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:57.134 18469 DEBUG neutronclient.v2_0.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-1068e298-aa00-4a90-b6d4-bba7d3f35ab2 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:57.135 18469 DEBUG nova.network.base_api [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:33:57.137 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 106891201f604e969f9b5f6067cd01f8 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:57.154 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 106891201f604e969f9b5f6067cd01f8 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:57.155 18469 DEBUG oslo_concurrency.lockutils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Releasing semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:33:57.156 18469 DEBUG oslo_concurrency.lockutils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker.instance_claim" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:33:57.160 18469 DEBUG nova.compute.resource_tracker [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Memory overhead for 512 MB instance; 0 MB instance_claim /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:147
2019-03-29 10:33:57.160 18469 DEBUG nova.compute.resource_tracker [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Disk overhead for 1 GB instance; 0 GB instance_claim /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:150
2019-03-29 10:33:57.162 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 366b3650f2364b229041e350d6a667e2 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:57.175 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 366b3650f2364b229041e350d6a667e2 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:57.179 18469 INFO nova.compute.claims [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Attempting claim: memory 512 MB, disk 1 GB, vcpus 1 CPU
2019-03-29 10:33:57.180 18469 INFO nova.compute.claims [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Total memory: 8191 MB, used: 512.00 MB
2019-03-29 10:33:57.181 18469 INFO nova.compute.claims [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] memory limit: 12286.50 MB, free: 11774.50 MB
2019-03-29 10:33:57.181 18469 INFO nova.compute.claims [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Total disk: 47 GB, used: 0.00 GB
2019-03-29 10:33:57.182 18469 INFO nova.compute.claims [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] disk limit: 47.00 GB, free: 47.00 GB
2019-03-29 10:33:57.183 18469 INFO nova.compute.claims [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Total vcpu: 2 VCPU, used: 0.00 VCPU
2019-03-29 10:33:57.183 18469 INFO nova.compute.claims [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] vcpu limit: 32.00 VCPU, free: 32.00 VCPU
2019-03-29 10:33:57.184 18469 DEBUG nova.objects.instance [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'numa_topology' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:33:57.185 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: f93e0fa6b11a4b5b9175ed15ecdc3fac exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:57.196 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: f93e0fa6b11a4b5b9175ed15ecdc3fac __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:57.198 18469 DEBUG nova.virt.hardware [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Require both a host and instance NUMA topology to fit instance on host. numa_fit_instance_to_host /usr/lib/python2.7/site-packages/nova/virt/hardware.py:1328
2019-03-29 10:33:57.198 18469 INFO nova.compute.claims [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Claim successful
2019-03-29 10:33:57.203 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 8d7de634cc404a488472dd1e13543bee exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:57.300 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 8d7de634cc404a488472dd1e13543bee __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:57.307 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: eb627c6a9ec8479e96c82ab73e048b19 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:57.318 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: eb627c6a9ec8479e96c82ab73e048b19 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:57.333 18469 DEBUG nova.scheduler.client.report [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Sending allocation for instance {'MEMORY_MB': 512, 'VCPU': 1} _allocate_for_instance /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:664
2019-03-29 10:33:57.385 18469 INFO nova.scheduler.client.report [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Submitted allocation for instance
2019-03-29 10:33:57.394 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 2818e46b52414fbfb060d4747d57ebd7 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:57.432 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 2818e46b52414fbfb060d4747d57ebd7 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:57.434 18469 DEBUG nova.scheduler.client.report [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:33:57.464 18469 DEBUG nova.scheduler.client.report [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Updating our resource provider generation from 30 to 31 _get_inventory_and_update_provider_generation /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:445
2019-03-29 10:33:57.465 18469 DEBUG oslo_concurrency.lockutils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" released by "nova.compute.resource_tracker.instance_claim" :: held 0.309s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:33:57.467 18469 INFO nova.virt.libvirt.driver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Creating image
2019-03-29 10:33:57.468 18469 DEBUG nova.virt.libvirt.driver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Ensure instance console log exists: /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/console.log _ensure_console_log_for_instance /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:3019
2019-03-29 10:33:57.471 18469 DEBUG nova.virt.libvirt.driver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Start _get_guest_xml network_info=[{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] disk_info={'disk_bus': 'virtio', 'cdrom_bus': 'ide', 'mapping': {u'/dev/vda': {'bus': u'virtio', 'boot_index': '1', 'type': u'disk', 'dev': u'vda'}, 'root': {'bus': u'virtio', 'boot_index': '1', 'type': u'disk', 'dev': u'vda'}, 'disk.config': {'bus': 'ide', 'type': 'cdrom', 'dev': 'hda'}}} image_meta=ImageMeta(checksum=<?>,container_format=<?>,created_at=<?>,direct_url=<?>,disk_format=<?>,id=<?>,min_disk=1,min_ram=0,name=<?>,owner=<?>,properties=ImageMetaProps,protected=<?>,size=<?>,status=<?>,tags=<?>,updated_at=<?>,virtual_size=<?>,visibility=<?>) rescue=None block_device_info={'swap': None, 'root_device_name': u'/dev/vda', 'ephemerals': [], 'block_device_mapping': [{'guest_format': None, 'boot_index': 0, 'mount_device': u'/dev/vda', 'connection_info': {u'driver_volume_type': u'iscsi', 'connector': {'platform': 'x86_64', 'host': 'com58', 'do_local_attach': False, 'ip': '172.30.126.58', 'os_type': 'linux2', 'multipath': False, 'initiator': u'iqn.1994-05.com.redhat:9affbb458449'}, 'serial': u'78a56ddc-ee21-4278-991e-17b30d68fa6e', u'data': {u'access_mode': u'rw', u'target_discovered': False, u'encrypted': False, u'qos_specs': None, u'target_iqn': u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_portal': u'172.30.126.56:3260', u'volume_id': u'78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_lun': 0, u'auth_password': u'***', u'auth_username': u'PutS9jPtTsLadXTr42qr', u'auth_method': u'CHAP'}}, 'disk_bus': u'virtio', 'device_type': u'disk', 'delete_on_termination': False}]} _get_guest_xml /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:4971
2019-03-29 10:33:57.486 18469 DEBUG nova.virt.hardware [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Getting desirable topologies for flavor Flavor(created_at=2019-03-25T11:43:43Z,deleted=False,deleted_at=None,disabled=False,ephemeral_gb=0,extra_specs={},flavorid='1',id=1,is_public=True,memory_mb=512,name='m1.tiny',projects=<?>,root_gb=1,rxtx_factor=1.0,swap=0,updated_at=None,vcpu_weight=0,vcpus=1) and image_meta ImageMeta(checksum=<?>,container_format=<?>,created_at=<?>,direct_url=<?>,disk_format=<?>,id=<?>,min_disk=1,min_ram=0,name=<?>,owner=<?>,properties=ImageMetaProps,protected=<?>,size=<?>,status=<?>,tags=<?>,updated_at=<?>,virtual_size=<?>,visibility=<?>), allow threads: True _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:560
2019-03-29 10:33:57.487 18469 DEBUG nova.virt.hardware [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Flavor limits 65536:65536:65536 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:306
2019-03-29 10:33:57.487 18469 DEBUG nova.virt.hardware [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Image limits 65536:65536:65536 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:317
2019-03-29 10:33:57.488 18469 DEBUG nova.virt.hardware [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Flavor pref -1:-1:-1 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:340
2019-03-29 10:33:57.488 18469 DEBUG nova.virt.hardware [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Image pref -1:-1:-1 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:359
2019-03-29 10:33:57.489 18469 DEBUG nova.virt.hardware [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Chosen -1:-1:-1 limits 65536:65536:65536 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:388
2019-03-29 10:33:57.489 18469 DEBUG nova.virt.hardware [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Topology preferred VirtCPUTopology(cores=-1,sockets=-1,threads=-1), maximum VirtCPUTopology(cores=65536,sockets=65536,threads=65536) _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:564
2019-03-29 10:33:57.489 18469 DEBUG nova.virt.hardware [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Build topologies for 1 vcpu(s) 1:1:1 _get_possible_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:427
2019-03-29 10:33:57.490 18469 DEBUG nova.virt.hardware [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Got 1 possible topologies _get_possible_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:454
2019-03-29 10:33:57.490 18469 DEBUG nova.virt.hardware [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Possible topologies [VirtCPUTopology(cores=1,sockets=1,threads=1)] _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:569
2019-03-29 10:33:57.491 18469 DEBUG nova.virt.hardware [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Sorted desired topologies [VirtCPUTopology(cores=1,sockets=1,threads=1)] _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:594
2019-03-29 10:33:57.491 18469 DEBUG nova.objects.instance [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'vcpu_model' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:33:57.492 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 88a833b11e784948a490de5a2162638b exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:57.506 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 88a833b11e784948a490de5a2162638b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:57.512 18469 DEBUG nova.virt.libvirt.volume.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Calling os-brick to attach iSCSI Volume connect_volume /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/iscsi.py:63
2019-03-29 10:33:57.513 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> connect_volume: call u"{'args': (<os_brick.initiator.connectors.iscsi.ISCSIConnector object at 0x5ae9b50>, {u'access_mode': u'rw', u'target_discovered': False, u'encrypted': False, u'qos_specs': None, u'target_iqn': u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_portal': u'172.30.126.56:3260', u'volume_id': u'78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_lun': 0, u'auth_password': u'***', u'auth_username': u'PutS9jPtTsLadXTr42qr', u'auth_method': u'CHAP'}), 'kwargs': {}}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:33:57.513 18469 DEBUG oslo_concurrency.lockutils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "connect_volume" acquired by "os_brick.initiator.connectors.iscsi.connect_volume" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:33:57.514 18469 INFO os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Multipath discovery for iSCSI not enabled.
2019-03-29 10:33:57.514 18469 INFO os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Trying to connect to iSCSI portal 172.30.126.56:3260
2019-03-29 10:33:57.516 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.517 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.522 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260" returned: 21 in 0.006s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.522 18469 DEBUG oslo.privsep.daemon [-] u'iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260' failed. Not Retrying. out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.522 18469 DEBUG oslo.privsep.daemon [-] privsep: Exception during request[97285936]: Unexpected error while running command.
Command: iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260
Exit code: 21
Stdout: u''
Stderr: u'iscsiadm: No records found\n' out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.522 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (5, 'oslo_concurrency.processutils.ProcessExecutionError', (u'', u'iscsiadm: No records found\n', 21, u'iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260', None)) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.523 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--interface', 'default', '--op', 'new'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.524 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --interface default --op new out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.529 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --interface default --op new" returned: 0 in 0.005s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.529 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, ('New iSCSI node [tcp:[hw=,ip=,net_if=,iscsi_if=default] 172.30.126.56,3260,-1 iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e] added\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.530 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--interface', 'default', '--op', 'new'): stdout=New iSCSI node [tcp:[hw=,ip=,net_if=,iscsi_if=default] 172.30.126.56,3260,-1 iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e] added
 stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:33:57.530 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.session.auth.authmethod', '-v', u'CHAP'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.531 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.authmethod -v CHAP out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.535 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.authmethod -v CHAP" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.535 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.536 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.session.auth.authmethod', '-v', u'CHAP'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:33:57.536 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.session.auth.username', '-v', u'PutS9jPtTsLadXTr42qr'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.537 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.username -v PutS9jPtTsLadXTr42qr out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.570 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.username -v PutS9jPtTsLadXTr42qr" returned: 0 in 0.033s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.570 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.570 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.session.auth.username', '-v', u'PutS9jPtTsLadXTr42qr'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:33:57.571 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.session.auth.password', '-v', u'TPnqk7LML2MKpPv4'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.572 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.password -v *** out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.576 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.password -v ***" returned: 0 in 0.005s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.577 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.577 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.session.auth.password', '-v', u'***'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:33:57.578 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'session'), {'check_exit_code': (0, 1, 21)}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.578 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m session out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.581 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m session" returned: 21 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.582 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, ('', 'iscsiadm: No active sessions.\n')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.582 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ['-m', 'session']: stdout= stderr=iscsiadm: No active sessions.
 _run_iscsiadm_bare /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:824
2019-03-29 10:33:57.583 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--login'), {'attempts': 1, 'check_exit_code': (0, 255), 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.584 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --login out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.646 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --login" returned: 0 in 0.063s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.647 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, ('Logging in to [iface: default, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] (multiple)\nLogin to [iface: default, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] successful.\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.647 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--login',): stdout=Logging in to [iface: default, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] (multiple)
Login to [iface: default, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] successful.
 stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:33:57.649 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.startup', '-v', 'automatic'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.649 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.startup -v automatic out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.653 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.startup -v automatic" returned: 0 in 0.005s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.653 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.654 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.startup', '-v', 'automatic'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:33:57.654 18469 INFO os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ISCSI volume not yet found at: [u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0']. Will rescan & retry.  Try number: 0.
2019-03-29 10:33:57.656 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--rescan'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.656 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --rescan out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.689 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --rescan" returned: 0 in 0.034s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.690 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, ('Rescanning session [sid: 10, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260]\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:57.690 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--rescan',): stdout=Rescanning session [sid: 10, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260]
 stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:33:58.691 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Found iSCSI node [u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0'] (after 1 rescans) connect_volume /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:437
2019-03-29 10:33:58.694 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'os_brick.privileged.rootwrap.execute_root', ('/lib/udev/scsi_id', '--page', '0x83', '--whitelisted', u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.695 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): /lib/udev/scsi_id --page 0x83 --whitelisted /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.703 18469 DEBUG oslo.privsep.daemon [-] CMD "/lib/udev/scsi_id --page 0x83 --whitelisted /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0" returned: 0 in 0.011s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.704 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, ('36001405fb81b00707464d729f24ff6c3\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.704 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Device WWN = '36001405fb81b00707464d729f24ff6c3' connect_volume /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:444
2019-03-29 10:33:58.704 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] connect_volume returning {'path': u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0', 'scsi_wwn': u'36001405fb81b00707464d729f24ff6c3', 'type': 'block'} connect_volume /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:456
2019-03-29 10:33:58.705 18469 DEBUG oslo_concurrency.lockutils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "connect_volume" released by "os_brick.initiator.connectors.iscsi.connect_volume" :: held 1.191s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:33:58.705 18469 DEBUG os_brick.initiator.connectors.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== connect_volume: return (1192ms) {'path': u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0', 'scsi_wwn': u'36001405fb81b00707464d729f24ff6c3', 'type': u'block'} trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:33:58.705 18469 DEBUG nova.virt.libvirt.volume.iscsi [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Attached iSCSI volume {'path': u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0', 'scsi_wwn': u'36001405fb81b00707464d729f24ff6c3', 'type': 'block'} connect_volume /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/iscsi.py:65
2019-03-29 10:33:58.710 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 22a2f3bed9b2424c9538b241d625efce exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:58.747 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 22a2f3bed9b2424c9538b241d625efce __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:58.750 18469 DEBUG nova.virt.libvirt.vif [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] vif_type=ovs instance=Instance(access_ip_v4=None,access_ip_v6=None,architecture='x86_64',auto_disk_config=False,availability_zone='nova',cell_name=None,cleaned=True,config_drive='True',created_at=2019-03-29T02:02:33Z,default_ephemeral_device=None,default_swap_device=None,deleted=False,deleted_at=None,device_metadata=<?>,disable_terminate=False,display_description='vm001',display_name='vm001',ec2_ids=<?>,ephemeral_gb=0,ephemeral_key_uuid=None,fault=<?>,flavor=Flavor(1),host='com58',hostname='vm001',id=24,image_ref='',info_cache=InstanceInfoCache,instance_type_id=1,kernel_id='',key_data=None,key_name=None,keypairs=<?>,launch_index=0,launched_at=2019-03-29T02:12:27Z,launched_on='com58',locked=False,locked_by=None,memory_mb=512,metadata={},migration_context=<?>,new_flavor=None,node='com58',numa_topology=None,old_flavor=None,os_type=None,pci_devices=<?>,pci_requests=<?>,power_state=4,progress=0,project_id='d4bbd972ca1b463ba028ccd1df983917',ramdisk_id='',reservation_id='r-x56iqcqr',root_device_name='/dev/vda',root_gb=1,security_groups=SecurityGroupList,services=<?>,shutdown_terminate=False,system_metadata={boot_roles='admin',clean_attempts='2',image_architecture='x86_64',image_base_image_ref='',image_min_disk='1',image_min_ram='0'},tags=<?>,task_state='spawning',terminated_at=None,updated_at=2019-03-29T02:33:53Z,user_data=None,user_id='9e9e53917dda421083fa6af425c6bfbf',uuid=f5a19c94-1a45-4ea0-9386-77c10705c825,vcpu_model=VirtCPUModel,vcpus=1,vm_mode=None,vm_state='shelved_offloaded') vif={"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} virt_type=qemu get_config /usr/lib/python2.7/site-packages/nova/virt/libvirt/vif.py:529
2019-03-29 10:33:58.751 18469 DEBUG nova.network.os_vif_util [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converting VIF {"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:413
2019-03-29 10:33:58.752 18469 DEBUG nova.network.os_vif_util [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converted object VIFBridge(active=False,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:425
2019-03-29 10:33:58.759 18469 DEBUG nova.objects.instance [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'pci_devices' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:33:58.760 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: fc2feaa7329d4bda9f0b6aab1b0038c7 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:58.773 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: fc2feaa7329d4bda9f0b6aab1b0038c7 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:58.775 18469 DEBUG nova.virt.libvirt.driver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] End _get_guest_xml xml=<domain type="qemu">
  <uuid>f5a19c94-1a45-4ea0-9386-77c10705c825</uuid>
  <name>instance-00000018</name>
  <memory>524288</memory>
  <vcpu>1</vcpu>
  <metadata>
    <nova:instance xmlns:nova="http://openstack.org/xmlns/libvirt/nova/1.0">
      <nova:package version="0.0.0-1.el7.ceos"/>
      <nova:name>vm001</nova:name>
      <nova:creationTime>2019-03-29 02:33:57</nova:creationTime>
      <nova:flavor name="m1.tiny">
        <nova:memory>512</nova:memory>
        <nova:disk>1</nova:disk>
        <nova:swap>0</nova:swap>
        <nova:ephemeral>0</nova:ephemeral>
        <nova:vcpus>1</nova:vcpus>
      </nova:flavor>
      <nova:owner>
        <nova:user uuid="9e9e53917dda421083fa6af425c6bfbf">admin</nova:user>
        <nova:project uuid="d4bbd972ca1b463ba028ccd1df983917">admin</nova:project>
      </nova:owner>
    </nova:instance>
  </metadata>
  <sysinfo type="smbios">
    <system>
      <entry name="manufacturer">RDO</entry>
      <entry name="product">OpenStack Compute</entry>
      <entry name="version">0.0.0-1.el7.ceos</entry>
      <entry name="serial">b72f0c91-de47-47b5-9c10-43dfb0050cac</entry>
      <entry name="uuid">f5a19c94-1a45-4ea0-9386-77c10705c825</entry>
      <entry name="family">Virtual Machine</entry>
    </system>
  </sysinfo>
  <os>
    <type>hvm</type>
    <boot dev="hd"/>
    <smbios mode="sysinfo"/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cputune>
    <shares>1024</shares>
  </cputune>
  <clock offset="utc"/>
  <cpu match="exact">
    <topology sockets="1" cores="1" threads="1"/>
  </cpu>
  <devices>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw" cache="none"/>
      <source file="/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.config"/>
      <target bus="ide" dev="hda"/>
    </disk>
    <disk type="block" device="disk">
      <driver name="qemu" type="raw" cache="none" io="native"/>
      <source dev="/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0"/>
      <target bus="virtio" dev="vda"/>
      <serial>78a56ddc-ee21-4278-991e-17b30d68fa6e</serial>
    </disk>
    <interface type="bridge">
      <mac address="fa:16:3e:29:72:d6"/>
      <model type="virtio"/>
      <driver name="qemu"/>
      <source bridge="qbrb3249515-3a"/>
      <target dev="tapb3249515-3a"/>
    </interface>
    <serial type="pty">
      <log file="/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/console.log" append="off"/>
    </serial>
    <input type="tablet" bus="usb"/>
    <graphics type="vnc" autoport="yes" keymap="en-us" listen="0.0.0.0"/>
    <video>
      <model type="cirrus"/>
    </video>
    <memballoon model="virtio">
      <stats period="10"/>
    </memballoon>
  </devices>
</domain>
 _get_guest_xml /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:4978
2019-03-29 10:33:58.775 18469 DEBUG nova.compute.manager [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Preparing to wait for external event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a prepare_for_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:328
2019-03-29 10:33:58.776 18469 DEBUG oslo_concurrency.lockutils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._create_or_get_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:33:58.776 18469 DEBUG oslo_concurrency.lockutils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._create_or_get_event" :: held 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:33:58.777 18469 DEBUG nova.virt.libvirt.vif [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] vif_type=ovs instance=Instance(access_ip_v4=None,access_ip_v6=None,architecture='x86_64',auto_disk_config=False,availability_zone='nova',cell_name=None,cleaned=True,config_drive='True',created_at=2019-03-29T02:02:33Z,default_ephemeral_device=None,default_swap_device=None,deleted=False,deleted_at=None,device_metadata=<?>,disable_terminate=False,display_description='vm001',display_name='vm001',ec2_ids=<?>,ephemeral_gb=0,ephemeral_key_uuid=None,fault=<?>,flavor=Flavor(1),host='com58',hostname='vm001',id=24,image_ref='',info_cache=InstanceInfoCache,instance_type_id=1,kernel_id='',key_data=None,key_name=None,keypairs=<?>,launch_index=0,launched_at=2019-03-29T02:12:27Z,launched_on='com58',locked=False,locked_by=None,memory_mb=512,metadata={},migration_context=<?>,new_flavor=None,node='com58',numa_topology=None,old_flavor=None,os_type=None,pci_devices=PciDeviceList,pci_requests=<?>,power_state=4,progress=0,project_id='d4bbd972ca1b463ba028ccd1df983917',ramdisk_id='',reservation_id='r-x56iqcqr',root_device_name='/dev/vda',root_gb=1,security_groups=SecurityGroupList,services=<?>,shutdown_terminate=False,system_metadata={boot_roles='admin',clean_attempts='2',image_architecture='x86_64',image_base_image_ref='',image_min_disk='1',image_min_ram='0'},tags=<?>,task_state='spawning',terminated_at=None,updated_at=2019-03-29T02:33:53Z,user_data=None,user_id='9e9e53917dda421083fa6af425c6bfbf',uuid=f5a19c94-1a45-4ea0-9386-77c10705c825,vcpu_model=VirtCPUModel,vcpus=1,vm_mode=None,vm_state='shelved_offloaded') vif={"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} plug /usr/lib/python2.7/site-packages/nova/virt/libvirt/vif.py:776
2019-03-29 10:33:58.778 18469 DEBUG nova.network.os_vif_util [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converting VIF {"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:413
2019-03-29 10:33:58.779 18469 DEBUG nova.network.os_vif_util [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converted object VIFBridge(active=False,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:425
2019-03-29 10:33:58.780 18469 DEBUG os_vif [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Plugging vif VIFBridge(active=False,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') plug /usr/lib/python2.7/site-packages/os_vif/__init__.py:79
2019-03-29 10:33:58.782 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'vif_plug_ovs.linux_net.ensure_bridge', (u'qbrb3249515-3a',), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.783 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl addbr qbrb3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.792 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl addbr qbrb3249515-3a" returned: 0 in 0.006s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.792 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl setfd qbrb3249515-3a 0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.798 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl setfd qbrb3249515-3a 0" returned: 0 in 0.010s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.798 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl stp qbrb3249515-3a off out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.800 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl stp qbrb3249515-3a off" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.801 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): tee /sys/class/net/qbrb3249515-3a/bridge/multicast_snooping out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.803 18469 DEBUG oslo.privsep.daemon [-] CMD "tee /sys/class/net/qbrb3249515-3a/bridge/multicast_snooping" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.804 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): tee /proc/sys/net/ipv6/conf/qbrb3249515-3a/disable_ipv6 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.807 18469 DEBUG oslo.privsep.daemon [-] CMD "tee /proc/sys/net/ipv6/conf/qbrb3249515-3a/disable_ipv6" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.807 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.808 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'vif_plug_ovs.linux_net.create_veth_pair', ('qvbb3249515-3a', 'qvob3249515-3a', 1500), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.809 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link add qvbb3249515-3a type veth peer name qvob3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.821 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link add qvbb3249515-3a type veth peer name qvob3249515-3a" returned: 0 in 0.011s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.821 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvbb3249515-3a up out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.828 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvbb3249515-3a up" returned: 0 in 0.009s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.829 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvbb3249515-3a promisc on out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.832 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvbb3249515-3a promisc on" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.833 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvbb3249515-3a mtu 1500 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.836 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvbb3249515-3a mtu 1500" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.836 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvob3249515-3a up out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.840 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvob3249515-3a up" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.840 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvob3249515-3a promisc on out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.846 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvob3249515-3a promisc on" returned: 0 in 0.006s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.846 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvob3249515-3a mtu 1500 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.848 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvob3249515-3a mtu 1500" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.849 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.849 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'vif_plug_ovs.linux_net.add_bridge_port', (u'qbrb3249515-3a', 'qvbb3249515-3a'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.849 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qbrb3249515-3a up out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.853 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qbrb3249515-3a up" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.853 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl addif qbrb3249515-3a qvbb3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.860 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl addif qbrb3249515-3a qvbb3249515-3a" returned: 0 in 0.006s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.860 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.862 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'vif_plug_ovs.linux_net.ensure_ovs_bridge', (u'br-int', 'system'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.862 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ovs-vsctl -- --may-exist add-br br-int -- set Bridge br-int datapath_type=system out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.873 18469 DEBUG oslo.privsep.daemon [-] CMD "ovs-vsctl -- --may-exist add-br br-int -- set Bridge br-int datapath_type=system" returned: 0 in 0.011s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.873 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.875 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285936]: (3, 'vif_plug_ovs.linux_net.create_ovs_vif_port', (u'br-int', 'qvob3249515-3a', 'b3249515-3aab-439f-ba9c-bc498756871a', u'fa:16:3e:29:72:d6', 'f5a19c94-1a45-4ea0-9386-77c10705c825', 1500), {'timeout': 120}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.875 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ovs-vsctl --timeout=120 -- --if-exists del-port qvob3249515-3a -- add-port br-int qvob3249515-3a -- set Interface qvob3249515-3a external-ids:iface-id=b3249515-3aab-439f-ba9c-bc498756871a external-ids:iface-status=active external-ids:attached-mac=fa:16:3e:29:72:d6 external-ids:vm-uuid=f5a19c94-1a45-4ea0-9386-77c10705c825 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.888 18469 DEBUG oslo.privsep.daemon [-] CMD "ovs-vsctl --timeout=120 -- --if-exists del-port qvob3249515-3a -- add-port br-int qvob3249515-3a -- set Interface qvob3249515-3a external-ids:iface-id=b3249515-3aab-439f-ba9c-bc498756871a external-ids:iface-status=active external-ids:attached-mac=fa:16:3e:29:72:d6 external-ids:vm-uuid=f5a19c94-1a45-4ea0-9386-77c10705c825" returned: 0 in 0.013s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.888 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvob3249515-3a mtu 1500 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.909 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvob3249515-3a mtu 1500" returned: 0 in 0.020s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.909 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285936]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:33:58.909 18469 INFO os_vif [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Successfully plugged vif VIFBridge(active=False,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a')
2019-03-29 10:33:58.959 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: d07a89af83fd4010af42f5928608e3e6 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:59.020 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: d07a89af83fd4010af42f5928608e3e6 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:59.023 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 227597cd7241447faf9d8c3c459ad8ca exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:59.033 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 227597cd7241447faf9d8c3c459ad8ca __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:59.039 18469 INFO nova.virt.libvirt.driver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Using config drive
2019-03-29 10:33:59.113 18469 DEBUG neutronclient.v2_0.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-5eb6907d-97d1-4837-b182-7f6b1c1a4f9e _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:59.183 18469 DEBUG neutronclient.v2_0.client [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/security-groups.json?id=4ee28088-03e4-414f-88d4-3c593382000b used request id req-67a46107-2abd-4f4f-b4cb-11fba6d54456 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:33:59.185 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: dd27b4260359437d81b067f1cb66b7ab exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:59.198 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: dd27b4260359437d81b067f1cb66b7ab __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:59.201 18469 DEBUG nova.objects.instance [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'ec2_ids' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:33:59.207 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: e52c547c941740f09cfa65f2936159dd exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:59.216 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: e52c547c941740f09cfa65f2936159dd __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:59.218 18469 INFO nova.virt.libvirt.driver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Creating config drive at /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.config
2019-03-29 10:33:59.221 18469 DEBUG oslo_concurrency.processutils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): genisoimage -o /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.config -ldots -allow-lowercase -allow-multidot -l -publisher OpenStack Compute 0.0.0-1.el7.ceos -quiet -J -r -V config-2 /tmp/tmpn9QYFn execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:33:59.243 18469 DEBUG oslo_concurrency.processutils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "genisoimage -o /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.config -ldots -allow-lowercase -allow-multidot -l -publisher OpenStack Compute 0.0.0-1.el7.ceos -quiet -J -r -V config-2 /tmp/tmpn9QYFn" returned: 0 in 0.022s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:33:59.471 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553826839.47, f5a19c94-1a45-4ea0-9386-77c10705c825 => Started> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:33:59.472 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Started (Lifecycle Event)
2019-03-29 10:33:59.474 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 0b7c728742bb4fbba0aeecf215f9a284 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:59.513 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 0b7c728742bb4fbba0aeecf215f9a284 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:59.515 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:33:59.520 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553826839.47, f5a19c94-1a45-4ea0-9386-77c10705c825 => Paused> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:33:59.521 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Paused (Lifecycle Event)
2019-03-29 10:33:59.523 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: ddfc1321381341ad8a83bc3bd9bef255 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:59.561 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: ddfc1321381341ad8a83bc3bd9bef255 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:59.563 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:33:59.567 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Synchronizing instance power state after lifecycle event "Paused"; current vm_state: shelved_offloaded, current task_state: spawning, current DB power_state: 4, VM power_state: 3 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:33:59.570 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: f9f8bdb091d74d3cbf2a3e5c53b1d15a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:33:59.610 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: f9f8bdb091d74d3cbf2a3e5c53b1d15a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:33:59.612 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] During sync_power_state the instance has a pending task (spawning). Skip.
2019-03-29 10:34:01.517 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 41afec375ad64f8195367638cbb3c8a7 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:34:01.521 18469 DEBUG nova.compute.manager [req-31bd696f-80ac-4dcc-84b5-532773c7f4ac 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:34:01.521 18469 DEBUG oslo_concurrency.lockutils [req-31bd696f-80ac-4dcc-84b5-532773c7f4ac 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:34:01.522 18469 DEBUG oslo_concurrency.lockutils [req-31bd696f-80ac-4dcc-84b5-532773c7f4ac 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._pop_event" :: held 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:34:01.522 18469 DEBUG nova.compute.manager [req-31bd696f-80ac-4dcc-84b5-532773c7f4ac 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Processing event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a _process_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6816
2019-03-29 10:34:01.525 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553826841.52, f5a19c94-1a45-4ea0-9386-77c10705c825 => Resumed> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:34:01.525 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Resumed (Lifecycle Event)
2019-03-29 10:34:01.527 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: e70181a836c7449ba52db9f12be1071d exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:34:01.528 18469 DEBUG nova.virt.libvirt.driver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance is running spawn /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:2757
2019-03-29 10:34:01.530 18469 INFO nova.virt.libvirt.driver [-] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance spawned successfully.
2019-03-29 10:34:01.531 18469 DEBUG nova.compute.manager [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:34:01.536 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: cbefe4d5d7654e72add05cba926a9f6e exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:34:01.609 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: e70181a836c7449ba52db9f12be1071d __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:34:01.610 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:34:01.615 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Synchronizing instance power state after lifecycle event "Resumed"; current vm_state: shelved_offloaded, current task_state: spawning, current DB power_state: 4, VM power_state: 1 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:34:01.616 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 454ea872be6b481589b5be3e1d5c325e exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:34:01.695 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 454ea872be6b481589b5be3e1d5c325e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:34:01.696 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] During sync_power_state the instance has a pending task (spawning). Skip.
2019-03-29 10:34:01.696 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553826841.53, f5a19c94-1a45-4ea0-9386-77c10705c825 => Resumed> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:34:01.697 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Resumed (Lifecycle Event)
2019-03-29 10:34:01.699 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: d0e0fe4fb9244f66bfbd62354c95f429 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:34:01.767 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: d0e0fe4fb9244f66bfbd62354c95f429 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:34:01.768 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:34:01.772 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Synchronizing instance power state after lifecycle event "Resumed"; current vm_state: shelved_offloaded, current task_state: spawning, current DB power_state: 4, VM power_state: 1 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:34:01.774 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: cdb5429f8d4e4f31b026efbb56a990de exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:34:01.815 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: cbefe4d5d7654e72add05cba926a9f6e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:34:01.825 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CAST unique_id: 53da03b90b874415ba8ec5de8f1af866 FANOUT topic 'scheduler' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:539
2019-03-29 10:34:01.827 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: cdb5429f8d4e4f31b026efbb56a990de __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:34:01.828 18469 WARNING nova.image.glance [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:34:01.831 18469 DEBUG oslo_concurrency.lockutils [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825" released by "nova.compute.manager.do_unshelve_instance" :: held 9.339s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:34:01.832 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-0d5a36c9-d793-46aa-8350-5731e252d2c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: fcb8a851944846e98d3061a44464fd48 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:34:01.870 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: fcb8a851944846e98d3061a44464fd48 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:34:02.699 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._sync_scheduler_instance_info run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:34:02.700 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 09c0bc31977e444ca76cacce42b26b2d exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:34:02.731 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 09c0bc31977e444ca76cacce42b26b2d __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:34:02.732 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CAST unique_id: 7054da5a55514d01ae557d2c08c5bcd9 FANOUT topic 'scheduler' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:539
2019-03-29 10:34:03.349 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 5bf0ce50970c423bb11b15f315b8b1d9 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:34:03.391 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 5bf0ce50970c423bb11b15f315b8b1d9 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
