2019-03-29 10:11:53.753 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 08a9fe494ece4a9da50af1dfeb0575ca exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:11:53.784 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 08a9fe494ece4a9da50af1dfeb0575ca __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:03.756 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 8ece71f0d8604bbbac3ec6883fdd91e0 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:03.797 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 8ece71f0d8604bbbac3ec6883fdd91e0 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:12.577 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: d2e32501a5b94173b1f39326f0ba994b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:12:12.585 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: a31bfdc7b0d34ddbae672fc48542529a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:12.621 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a31bfdc7b0d34ddbae672fc48542529a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:12.622 10556 DEBUG oslo_concurrency.lockutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Acquired semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:12:12.622 10556 DEBUG nova.network.neutronv2.api [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:12:12.623 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: d7366ae565764bd5aa7778f2b966ee7a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:12.633 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: d7366ae565764bd5aa7778f2b966ee7a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:12.736 10556 DEBUG neutronclient.v2_0.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-8373ba85-2cbc-4528-8233-8bdd206f0985 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:12.871 10556 DEBUG neutronclient.v2_0.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-014cf5d0-c95c-4e9a-9691-d3045f0f0f14 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:12.898 10556 DEBUG neutronclient.v2_0.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.11&port_id=b3249515-3aab-439f-ba9c-bc498756871a used request id req-cb234788-b82f-4761-807b-cb6c5b20193b _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:12.967 10556 DEBUG neutronclient.v2_0.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-92e3ba49-fe90-44f0-8944-2c90aa1f253c _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:13.045 10556 DEBUG neutronclient.v2_0.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-eb99f20a-c8ad-40d5-bf8e-d3d801649046 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:13.045 10556 DEBUG nova.network.base_api [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": true, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:12:13.046 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 49127e4fb92542c9ab82eeb57d8e7924 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:13.062 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 49127e4fb92542c9ab82eeb57d8e7924 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:13.064 10556 DEBUG oslo_concurrency.lockutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Releasing semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:12:13.066 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 2ebe9f77afb34a1c8499bab6e51a1d2d exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:13.095 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 2ebe9f77afb34a1c8499bab6e51a1d2d __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:13.099 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: e6876b6afdff4c37aca197c3e6559c25 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:13.205 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: e6876b6afdff4c37aca197c3e6559c25 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:13.207 10556 WARNING nova.image.glance [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:12:13.211 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 277e7bb3793243be86b7ad7bfd0e3860 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:13.222 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 277e7bb3793243be86b7ad7bfd0e3860 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:13.223 10556 DEBUG nova.virt.libvirt.driver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Starting migrate_disk_and_power_off migrate_disk_and_power_off /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:7292
2019-03-29 10:12:13.227 10556 DEBUG nova.virt.libvirt.volume.remotefs [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Creating file /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/25d0f2254a31470dbbcbdf8d5b8c1b7d.tmp on remote host 172.30.126.58 create_file /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/remotefs.py:88
2019-03-29 10:12:13.228 10556 DEBUG oslo_concurrency.processutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): ssh -o BatchMode=yes 172.30.126.58 touch /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/25d0f2254a31470dbbcbdf8d5b8c1b7d.tmp execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:12:13.578 10556 DEBUG oslo_concurrency.processutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "ssh -o BatchMode=yes 172.30.126.58 touch /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/25d0f2254a31470dbbcbdf8d5b8c1b7d.tmp" returned: 1 in 0.351s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:12:13.579 10556 DEBUG oslo_concurrency.processutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] u'ssh -o BatchMode=yes 172.30.126.58 touch /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/25d0f2254a31470dbbcbdf8d5b8c1b7d.tmp' failed. Not Retrying. execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:433
2019-03-29 10:12:13.579 10556 DEBUG nova.virt.libvirt.volume.remotefs [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Creating directory /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825 on remote host 172.30.126.58 create_dir /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/remotefs.py:100
2019-03-29 10:12:13.580 10556 DEBUG oslo_concurrency.processutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): ssh -o BatchMode=yes 172.30.126.58 mkdir -p /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:12:13.759 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 81f926bfc56642089f108a8a855ca4f9 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:13.808 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 81f926bfc56642089f108a8a855ca4f9 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:13.890 10556 DEBUG oslo_concurrency.processutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "ssh -o BatchMode=yes 172.30.126.58 mkdir -p /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825" returned: 0 in 0.310s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:12:13.893 10556 DEBUG nova.virt.libvirt.driver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Shutting down instance from state 1 _clean_shutdown /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:2520
2019-03-29 10:12:16.902 10556 INFO nova.virt.libvirt.driver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance shutdown successfully after 3 seconds.
2019-03-29 10:12:17.116 10556 INFO nova.virt.libvirt.driver [-] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance destroyed successfully.
2019-03-29 10:12:17.117 10556 DEBUG nova.virt.libvirt.volume.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] calling os-brick to detach iSCSI Volume disconnect_volume /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/iscsi.py:72
2019-03-29 10:12:17.117 10556 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> disconnect_volume: call u"{'args': (<os_brick.initiator.connectors.iscsi.ISCSIConnector object at 0x596ea50>, {u'auth_password': u'***', u'target_discovered': False, u'encrypted': False, u'qos_specs': None, u'target_iqn': u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_portal': u'172.30.126.56:3260', u'volume_id': u'78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_lun': 0, u'access_mode': u'rw', u'auth_username': u'PutS9jPtTsLadXTr42qr', u'auth_method': u'CHAP'}, None), 'kwargs': {}}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:12:17.118 10556 DEBUG oslo_concurrency.lockutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "connect_volume" acquired by "os_brick.initiator.connectors.iscsi.disconnect_volume" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:17.118 10556 DEBUG os_brick.initiator.linuxscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Flushing IO for device /dev/sdb flush_device_io /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:146
2019-03-29 10:12:17.121 10556 DEBUG oslo.privsep.daemon [-] privsep: request[77878608]: (3, 'os_brick.privileged.rootwrap.execute_root', ('blockdev', '--flushbufs', u'/dev/sdb'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:17.121 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): blockdev --flushbufs /dev/sdb out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:17.125 10556 DEBUG oslo.privsep.daemon [-] CMD "blockdev --flushbufs /dev/sdb" returned: 0 in 0.005s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:17.125 10556 DEBUG oslo.privsep.daemon [-] privsep: reply[77878608]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:17.125 10556 DEBUG os_brick.initiator.linuxscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Remove SCSI device /dev/sdb with /sys/block/sdb/device/delete remove_scsi_device /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:69
2019-03-29 10:12:17.127 10556 DEBUG oslo.privsep.daemon [-] privsep: request[77878608]: (3, 'os_brick.privileged.rootwrap.execute_root', ('tee', '-a', u'/sys/block/sdb/device/delete'), {'process_input': '1'}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:17.127 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): tee -a /sys/block/sdb/device/delete out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:17.130 10556 DEBUG oslo.privsep.daemon [-] CMD "tee -a /sys/block/sdb/device/delete" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:17.131 10556 DEBUG oslo.privsep.daemon [-] privsep: reply[77878608]: (4, ('1', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:17.131 10556 DEBUG os_brick.initiator.linuxscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Checking to see if SCSI volume /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 has been removed. wait_for_volume_removal /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:77
2019-03-29 10:12:17.131 10556 DEBUG os_brick.initiator.linuxscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 still exists. wait_for_volume_removal /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:79
2019-03-29 10:12:17.132 10556 DEBUG os_brick.utils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Failed attempt 1 _print_stop /usr/lib/python2.7/site-packages/os_brick/utils.py:45
2019-03-29 10:12:17.132 10556 DEBUG os_brick.utils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Have been at this for 0.001 seconds _print_stop /usr/lib/python2.7/site-packages/os_brick/utils.py:47
2019-03-29 10:12:17.132 10556 DEBUG os_brick.utils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Sleeping for 2 seconds _backoff_sleep /usr/lib/python2.7/site-packages/os_brick/utils.py:40
2019-03-29 10:12:19.133 10556 DEBUG os_brick.initiator.linuxscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Checking to see if SCSI volume /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 has been removed. wait_for_volume_removal /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:77
2019-03-29 10:12:19.134 10556 DEBUG os_brick.initiator.linuxscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] SCSI volume /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 has been removed. wait_for_volume_removal /usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:83
2019-03-29 10:12:19.135 10556 DEBUG oslo.privsep.daemon [-] privsep: request[77878608]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.startup', '-v', 'manual'), {'attempts': 1, 'check_exit_code': (0, 21, 255), 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.135 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.startup -v manual out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.148 10556 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.startup -v manual" returned: 0 in 0.012s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.148 10556 DEBUG oslo.privsep.daemon [-] privsep: reply[77878608]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.149 10556 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.startup', '-v', 'manual'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:12:19.150 10556 DEBUG oslo.privsep.daemon [-] privsep: request[77878608]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--logout'), {'attempts': 1, 'check_exit_code': (0, 21, 255), 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.150 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --logout out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.160 10556 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --logout" returned: 0 in 0.009s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.160 10556 DEBUG oslo.privsep.daemon [-] privsep: reply[77878608]: (4, ('Logging out of session [sid: 11, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260]\nLogout of [sid: 11, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] successful.\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.161 10556 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--logout',): stdout=Logging out of session [sid: 11, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260]
Logout of [sid: 11, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] successful.
 stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:12:19.163 10556 DEBUG oslo.privsep.daemon [-] privsep: request[77878608]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'delete'), {'attempts': 5, 'check_exit_code': (0, 21, 255), 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.163 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op delete out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.167 10556 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op delete" returned: 0 in 0.005s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.167 10556 DEBUG oslo.privsep.daemon [-] privsep: reply[77878608]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.168 10556 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'delete'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:12:19.168 10556 DEBUG oslo_concurrency.lockutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "connect_volume" released by "os_brick.initiator.connectors.iscsi.disconnect_volume" :: held 2.050s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:19.169 10556 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== disconnect_volume: return (2050ms) None trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:12:19.169 10556 DEBUG nova.virt.libvirt.volume.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Disconnected iSCSI Volume vda disconnect_volume /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/iscsi.py:78
2019-03-29 10:12:19.172 10556 DEBUG nova.virt.libvirt.driver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] skipping disk /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 (vda) as it is a volume _get_instance_disk_info /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:7082
2019-03-29 10:12:19.173 10556 DEBUG oslo_concurrency.processutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): mv /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825 /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_resize execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:12:19.193 10556 DEBUG oslo_concurrency.processutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "mv /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825 /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_resize" returned: 0 in 0.020s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:12:19.195 10556 DEBUG nova.virt.libvirt.volume.remotefs [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Copying file /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_resize/disk.config to 172.30.126.58:/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.config copy_file /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/remotefs.py:112
2019-03-29 10:12:19.195 10556 DEBUG oslo_concurrency.processutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): scp -r /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_resize/disk.config 172.30.126.58:/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.config execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:12:19.592 10556 DEBUG oslo_concurrency.processutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "scp -r /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_resize/disk.config 172.30.126.58:/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.config" returned: 0 in 0.397s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:12:19.594 10556 DEBUG nova.virt.libvirt.volume.remotefs [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Copying file /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_resize/disk.info to 172.30.126.58:/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.info copy_file /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/remotefs.py:112
2019-03-29 10:12:19.594 10556 DEBUG oslo_concurrency.processutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): scp -r /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_resize/disk.info 172.30.126.58:/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.info execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:12:19.968 10556 DEBUG oslo_concurrency.processutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "scp -r /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_resize/disk.info 172.30.126.58:/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.info" returned: 0 in 0.374s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:12:19.970 10556 DEBUG os_brick.utils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> get_connector_properties: call u"{'execute': None, 'my_ip': '172.30.126.57', 'enforce_multipath': True, 'host': 'com57', 'root_helper': 'sudo nova-rootwrap /etc/nova/rootwrap.conf', 'multipath': False}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:12:19.974 10556 DEBUG oslo.privsep.daemon [-] privsep: request[77878608]: (3, 'os_brick.privileged.rootwrap.execute_root', ('cat', '/etc/iscsi/initiatorname.iscsi'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.974 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): cat /etc/iscsi/initiatorname.iscsi out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.977 10556 DEBUG oslo.privsep.daemon [-] CMD "cat /etc/iscsi/initiatorname.iscsi" returned: 0 in 0.005s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.978 10556 DEBUG oslo.privsep.daemon [-] privsep: reply[77878608]: (4, ('InitiatorName=iqn.1994-05.com.redhat:4d12e79a68be\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:19.978 10556 DEBUG os_brick.initiator.linuxfc [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:12:19.979 10556 DEBUG os_brick.initiator.linuxfc [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:12:19.979 10556 DEBUG os_brick.utils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== get_connector_properties: return (8ms) {'initiator': u'iqn.1994-05.com.redhat:4d12e79a68be', 'ip': u'172.30.126.57', 'platform': u'x86_64', 'host': u'com57', 'do_local_attach': False, 'os_type': u'linux2', 'multipath': False} trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:12:19.982 10556 DEBUG cinderclient.v2.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] REQ: curl -g -i -X POST http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}8909f64cb46a118d57e7cdb53d3762c4971c4edf" -d '{"os-terminate_connection": {"connector": {"platform": "x86_64", "host": "com57", "do_local_attach": false, "ip": "172.30.126.57", "os_type": "linux2", "multipath": false, "initiator": "iqn.1994-05.com.redhat:4d12e79a68be"}}}' _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:347
2019-03-29 10:12:21.496 10556 DEBUG cinderclient.v2.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] RESP: [202] Content-Type: text/html; charset=UTF-8 Content-Length: 0 X-Openstack-Request-Id: req-455d801d-ac55-4345-85e3-31514d6322c0 Date: Fri, 29 Mar 2019 02:12:21 GMT Connection: keep-alive 
RESP BODY: Omitted, Content-Type is set to text/html; charset=UTF-8. Only application/json responses have their bodies logged.
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:395
2019-03-29 10:12:21.496 10556 DEBUG cinderclient.v2.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] POST call to cinderv2 for http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action used request id req-455d801d-ac55-4345-85e3-31514d6322c0 request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:640
2019-03-29 10:12:21.499 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: cf29f078ebe349b5a03308541abda17d exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:21.525 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: cf29f078ebe349b5a03308541abda17d __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:21.529 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: acda87b83a414720b47b3a6afbfed101 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:21.638 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: acda87b83a414720b47b3a6afbfed101 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:21.640 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 803a706203204760960c9d3b292734bb exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:21.651 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 803a706203204760960c9d3b292734bb __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:21.655 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CAST unique_id: e4ce1b49c11445a485fe8fe66ee3174e exchange 'nova' topic 'compute.com58' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:21.656 10556 WARNING nova.image.glance [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:12:21.659 10556 DEBUG oslo_concurrency.lockutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._clear_events" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:21.659 10556 DEBUG oslo_concurrency.lockutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._clear_events" :: held 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:21.660 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: aaab065c09d145feb75bf8bfe7791463 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:21.695 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: aaab065c09d145feb75bf8bfe7791463 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:22.206 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 2a06da2ebb644500ba0a2059b328c1e4 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:12:22.208 10556 DEBUG nova.compute.manager [req-01c403e5-ae70-4a58-8833-81151e286efa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-vif-unplugged-b3249515-3aab-439f-ba9c-bc498756871a external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:12:22.209 10556 DEBUG oslo_concurrency.lockutils [req-01c403e5-ae70-4a58-8833-81151e286efa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:22.209 10556 DEBUG nova.compute.manager [req-01c403e5-ae70-4a58-8833-81151e286efa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:350
2019-03-29 10:12:22.210 10556 DEBUG oslo_concurrency.lockutils [req-01c403e5-ae70-4a58-8833-81151e286efa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._pop_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:22.210 10556 DEBUG nova.compute.manager [req-01c403e5-ae70-4a58-8833-81151e286efa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] No waiting events found dispatching network-vif-unplugged-b3249515-3aab-439f-ba9c-bc498756871a pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:366
2019-03-29 10:12:22.211 10556 WARNING nova.compute.manager [req-01c403e5-ae70-4a58-8833-81151e286efa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received unexpected event network-vif-unplugged-b3249515-3aab-439f-ba9c-bc498756871a for instance
2019-03-29 10:12:23.435 10556 DEBUG oslo_service.periodic_task [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Running periodic task ComputeManager._reclaim_queued_deletes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:23.436 10556 DEBUG nova.compute.manager [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CONF.reclaim_instance_interval <= 0, skipping... _reclaim_queued_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6556
2019-03-29 10:12:23.760 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: f108d7e4ddbc43469635cf2febe62600 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:23.799 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: f108d7e4ddbc43469635cf2febe62600 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:24.392 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: e2f21e13ec134e5a8f389d6f0e981189 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:12:24.395 10556 DEBUG nova.compute.manager [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-changed external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:12:24.396 10556 DEBUG oslo_concurrency.lockutils [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Acquired semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:12:24.396 10556 DEBUG nova.network.neutronv2.api [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:12:24.397 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] CALL msg_id: a83f479ec28f45d597a1d406beaa45e7 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:24.416 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a83f479ec28f45d597a1d406beaa45e7 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:24.435 10556 DEBUG oslo_service.periodic_task [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Running periodic task ComputeManager._instance_usage_audit run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:24.766 10556 DEBUG neutronclient.v2_0.client [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-4afbb8f7-5d75-4f53-823d-c24c97e0e2a9 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:24.839 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: a758248f780048b9988fb4cd09eb1b9a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:12:24.841 10556 DEBUG nova.compute.manager [req-abc98abf-3493-4433-adce-1a48d1d8bd01 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:12:24.842 10556 DEBUG oslo_concurrency.lockutils [req-abc98abf-3493-4433-adce-1a48d1d8bd01 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:24.842 10556 DEBUG nova.compute.manager [req-abc98abf-3493-4433-adce-1a48d1d8bd01 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:350
2019-03-29 10:12:24.843 10556 DEBUG oslo_concurrency.lockutils [req-abc98abf-3493-4433-adce-1a48d1d8bd01 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._pop_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:24.843 10556 DEBUG nova.compute.manager [req-abc98abf-3493-4433-adce-1a48d1d8bd01 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] No waiting events found dispatching network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:366
2019-03-29 10:12:24.843 10556 WARNING nova.compute.manager [req-abc98abf-3493-4433-adce-1a48d1d8bd01 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received unexpected event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a for instance
2019-03-29 10:12:25.031 10556 DEBUG neutronclient.v2_0.client [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-58e306e3-352b-4474-80cf-b518bebea137 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:25.126 10556 DEBUG neutronclient.v2_0.client [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.11&port_id=b3249515-3aab-439f-ba9c-bc498756871a used request id req-60bbbf8a-fc86-48e5-a7b3-8f1af5ddb62b _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:25.236 10556 DEBUG neutronclient.v2_0.client [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-2b711d29-f845-4401-8941-6d24335da168 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:25.287 10556 DEBUG neutronclient.v2_0.client [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-e8621970-bdf9-4dbd-a0e8-34d29e9b0571 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:25.289 10556 DEBUG nova.network.base_api [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:12:25.291 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] CALL msg_id: 0a1f7010100743cdb2d08141cf45dd70 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:25.305 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 0a1f7010100743cdb2d08141cf45dd70 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:25.306 10556 DEBUG oslo_concurrency.lockutils [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Releasing semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:12:26.434 10556 DEBUG oslo_service.periodic_task [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Running periodic task ComputeManager._poll_rebooting_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:27.433 10556 DEBUG oslo_service.periodic_task [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Running periodic task ComputeManager._check_instance_build_time run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:27.434 10556 DEBUG oslo_service.periodic_task [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Running periodic task ComputeManager._heal_instance_info_cache run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:27.434 10556 DEBUG nova.compute.manager [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Starting heal instance info cache _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5884
2019-03-29 10:12:27.435 10556 DEBUG nova.compute.manager [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Rebuilding the list of instances to heal _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5888
2019-03-29 10:12:27.437 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CALL msg_id: dc0ee27ab9a34feb9d1d92efcb9e8d4b exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:27.460 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: dc0ee27ab9a34feb9d1d92efcb9e8d4b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:27.461 10556 DEBUG nova.compute.manager [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Didn't find any instances for network info cache update. _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5960
2019-03-29 10:12:28.461 10556 DEBUG oslo_service.periodic_task [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Running periodic task ComputeManager._sync_scheduler_instance_info run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:28.463 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CALL msg_id: 169cf7d8522549df8c143cb124ee1eaa exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:28.522 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 169cf7d8522549df8c143cb124ee1eaa __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:28.523 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CAST unique_id: 2beae554be634d59836c2a6ce4423831 FANOUT topic 'scheduler' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:539
2019-03-29 10:12:29.333 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: d7b8e65ac34649cc894bd294651edfe1 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:12:29.337 10556 DEBUG nova.compute.manager [req-32fce7e9-0eb7-4ac7-b7f9-58e6d5aac0da 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:12:29.338 10556 DEBUG oslo_concurrency.lockutils [req-32fce7e9-0eb7-4ac7-b7f9-58e6d5aac0da 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:29.339 10556 DEBUG nova.compute.manager [req-32fce7e9-0eb7-4ac7-b7f9-58e6d5aac0da 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:350
2019-03-29 10:12:29.340 10556 DEBUG oslo_concurrency.lockutils [req-32fce7e9-0eb7-4ac7-b7f9-58e6d5aac0da 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._pop_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:29.340 10556 DEBUG nova.compute.manager [req-32fce7e9-0eb7-4ac7-b7f9-58e6d5aac0da 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] No waiting events found dispatching network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:366
2019-03-29 10:12:29.341 10556 WARNING nova.compute.manager [req-32fce7e9-0eb7-4ac7-b7f9-58e6d5aac0da 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received unexpected event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a for instance
2019-03-29 10:12:29.434 10556 DEBUG oslo_service.periodic_task [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Running periodic task ComputeManager._poll_rescued_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:30.435 10556 DEBUG oslo_service.periodic_task [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Running periodic task ComputeManager._poll_volume_usage run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:31.435 10556 DEBUG oslo_service.periodic_task [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Running periodic task ComputeManager.update_available_resource run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:31.437 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CALL msg_id: 72fb898b6e69414e9672a73e9be8e51f exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:31.463 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 72fb898b6e69414e9672a73e9be8e51f __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:31.469 10556 DEBUG nova.compute.resource_tracker [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Auditing locally available compute resources for com57 (node: com57) update_available_resource /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:534
2019-03-29 10:12:31.484 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CALL msg_id: 9b50caabf7c9432991a5e5ce03af2513 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:31.510 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 9b50caabf7c9432991a5e5ce03af2513 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:31.514 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CALL msg_id: 47d07f41d4fd41cfb5a81b61ef3d3533 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:31.527 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 47d07f41d4fd41cfb5a81b61ef3d3533 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:31.531 10556 WARNING nova.virt.libvirt.driver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Periodic task is updating the host stat, it is trying to get disk instance-00000018, but disk file was removed by concurrent operations such as resize.
2019-03-29 10:12:31.638 10556 DEBUG nova.compute.resource_tracker [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Hypervisor: free VCPUs: 2 _report_hypervisor_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:655
2019-03-29 10:12:31.638 10556 DEBUG nova.compute.resource_tracker [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Hypervisor/Node resource view: name=com57 free_ram=7104MB free_disk=44GB free_vcpus=2 pci_devices=[{"dev_id": "pci_0000_00_00_0", "product_id": "7190", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7190", "address": "0000:00:00.0"}, {"dev_id": "pci_0000_00_01_0", "product_id": "7191", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7191", "address": "0000:00:01.0"}, {"dev_id": "pci_0000_00_07_0", "product_id": "7110", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7110", "address": "0000:00:07.0"}, {"dev_id": "pci_0000_00_07_1", "product_id": "7111", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7111", "address": "0000:00:07.1"}, {"dev_id": "pci_0000_00_07_3", "product_id": "7113", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7113", "address": "0000:00:07.3"}, {"dev_id": "pci_0000_00_07_7", "product_id": "0740", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0740", "address": "0000:00:07.7"}, {"dev_id": "pci_0000_00_0f_0", "product_id": "0405", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0405", "address": "0000:00:0f.0"}, {"dev_id": "pci_0000_00_11_0", "product_id": "0790", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0790", "address": "0000:00:11.0"}, {"dev_id": "pci_0000_00_15_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.0"}, {"dev_id": "pci_0000_03_00_0", "product_id": "07c0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07c0", "address": "0000:03:00.0"}, {"dev_id": "pci_0000_00_15_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.1"}, {"dev_id": "pci_0000_00_15_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.2"}, {"dev_id": "pci_0000_00_15_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.3"}, {"dev_id": "pci_0000_00_15_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.4"}, {"dev_id": "pci_0000_00_15_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.5"}, {"dev_id": "pci_0000_00_15_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.6"}, {"dev_id": "pci_0000_00_15_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.7"}, {"dev_id": "pci_0000_00_16_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.0"}, {"dev_id": "pci_0000_0b_00_0", "product_id": "07b0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07b0", "address": "0000:0b:00.0"}, {"dev_id": "pci_0000_00_16_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.1"}, {"dev_id": "pci_0000_00_16_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.2"}, {"dev_id": "pci_0000_00_16_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.3"}, {"dev_id": "pci_0000_00_16_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.4"}, {"dev_id": "pci_0000_00_16_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.5"}, {"dev_id": "pci_0000_00_16_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.6"}, {"dev_id": "pci_0000_00_16_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.7"}, {"dev_id": "pci_0000_00_17_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.0"}, {"dev_id": "pci_0000_13_00_0", "product_id": "07b0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07b0", "address": "0000:13:00.0"}, {"dev_id": "pci_0000_00_17_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.1"}, {"dev_id": "pci_0000_00_17_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.2"}, {"dev_id": "pci_0000_00_17_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.3"}, {"dev_id": "pci_0000_00_17_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.4"}, {"dev_id": "pci_0000_00_17_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.5"}, {"dev_id": "pci_0000_00_17_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.6"}, {"dev_id": "pci_0000_00_17_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.7"}, {"dev_id": "pci_0000_00_18_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.0"}, {"dev_id": "pci_0000_00_18_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.1"}, {"dev_id": "pci_0000_00_18_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.2"}, {"dev_id": "pci_0000_00_18_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.3"}, {"dev_id": "pci_0000_00_18_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.4"}, {"dev_id": "pci_0000_00_18_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.5"}, {"dev_id": "pci_0000_00_18_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.6"}, {"dev_id": "pci_0000_00_18_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.7"}] _report_hypervisor_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:672
2019-03-29 10:12:31.639 10556 DEBUG oslo_concurrency.lockutils [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker._update_available_resource" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:31.641 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CALL msg_id: 0a55877776754041a4e960940f295d06 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:31.689 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 0a55877776754041a4e960940f295d06 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:31.690 10556 DEBUG nova.scheduler.client.report [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Refreshing aggregate associations for resource provider db732609-7867-486c-8e55-f52f70acfa62 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:12:31.719 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CALL msg_id: a183e57aa70e4d7884b9a3b01ea10d40 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:31.734 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a183e57aa70e4d7884b9a3b01ea10d40 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:31.749 10556 DEBUG nova.scheduler.client.report [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Deleting stale allocation for instance f5a19c94-1a45-4ea0-9386-77c10705c825 remove_deleted_instances /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:750
2019-03-29 10:12:31.785 10556 INFO nova.scheduler.client.report [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Deleted allocation for instance f5a19c94-1a45-4ea0-9386-77c10705c825
2019-03-29 10:12:31.786 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CALL msg_id: a10d1d89aa2a429c919461d4174c05fa exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:31.821 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a10d1d89aa2a429c919461d4174c05fa __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:31.822 10556 DEBUG nova.compute.resource_tracker [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Migration for instance f5a19c94-1a45-4ea0-9386-77c10705c825 refers to another host's instance! _pair_instances_to_migrations /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:568
2019-03-29 10:12:31.824 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CALL msg_id: 86444075c7404619a1cffd08a874b8c4 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:31.867 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 86444075c7404619a1cffd08a874b8c4 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:31.870 10556 INFO nova.compute.resource_tracker [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Updating from migration f5a19c94-1a45-4ea0-9386-77c10705c825
2019-03-29 10:12:31.871 10556 DEBUG nova.objects.instance [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Lazy-loading 'flavor' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:12:31.873 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CALL msg_id: cd80655ee8ad484fbc48635637f611be exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:31.921 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: cd80655ee8ad484fbc48635637f611be __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:31.925 10556 DEBUG nova.objects.instance [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Lazy-loading 'migration_context' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:12:31.926 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CALL msg_id: a2915fbaca0e44379f502ae11abaaefd exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:31.934 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a2915fbaca0e44379f502ae11abaaefd __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:31.937 10556 DEBUG nova.compute.resource_tracker [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Total usable vcpus: 2, total allocated vcpus: 1 _report_final_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:688
2019-03-29 10:12:31.937 10556 INFO nova.compute.resource_tracker [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Final resource view: name=com57 phys_ram=8191MB used_ram=1024MB phys_disk=47GB used_disk=1GB total_vcpus=2 used_vcpus=1 pci_stats=[]
2019-03-29 10:12:31.943 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] CALL msg_id: b2791af6c6c3499e803f92f51edc5a9e exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:31.969 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b2791af6c6c3499e803f92f51edc5a9e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:31.971 10556 DEBUG nova.scheduler.client.report [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Refreshing aggregate associations for resource provider db732609-7867-486c-8e55-f52f70acfa62 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:12:31.997 10556 DEBUG nova.compute.resource_tracker [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Compute_service record updated for com57:com57 _update_available_resource /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:626
2019-03-29 10:12:31.998 10556 DEBUG oslo_concurrency.lockutils [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Lock "compute_resources" released by "nova.compute.resource_tracker._update_available_resource" :: held 0.359s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:31.998 10556 DEBUG oslo_service.periodic_task [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Running periodic task ComputeManager._poll_unconfirmed_resizes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:32.114 10556 DEBUG nova.virt.driver [-] Emitting event <LifecycleEvent: 1553825537.11, f5a19c94-1a45-4ea0-9386-77c10705c825 => Stopped> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:12:32.115 10556 INFO nova.compute.manager [-] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Stopped (Lifecycle Event)
2019-03-29 10:12:32.116 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-3e013090-76f9-4546-8cf6-e4ecbe8ce8cd - - - - -] CALL msg_id: 1ed22ed09bb548aa837ffc6fe6dc9258 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:32.153 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 1ed22ed09bb548aa837ffc6fe6dc9258 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:32.155 10556 DEBUG nova.compute.manager [req-3e013090-76f9-4546-8cf6-e4ecbe8ce8cd - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:12:32.157 10556 DEBUG nova.compute.manager [req-3e013090-76f9-4546-8cf6-e4ecbe8ce8cd - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Synchronizing instance power state after lifecycle event "Stopped"; current vm_state: resized, current task_state: None, current DB power_state: 1, VM power_state: 4 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:12:32.159 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-3e013090-76f9-4546-8cf6-e4ecbe8ce8cd - - - - -] CALL msg_id: bb44653f36ee4bb197429260a5e7e234 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:32.198 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: bb44653f36ee4bb197429260a5e7e234 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:32.200 10556 INFO nova.compute.manager [req-3e013090-76f9-4546-8cf6-e4ecbe8ce8cd - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] During the sync_power process the instance has moved from host com58 to host com57
2019-03-29 10:12:33.763 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 96a1005ffcc846129711e258762a9026 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:33.809 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 96a1005ffcc846129711e258762a9026 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407








2019-03-29 10:12:43.762 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 15a6b389ec5147d4be1c2caba9a927da exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:43.813 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 15a6b389ec5147d4be1c2caba9a927da __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:45.359 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 806138c666754ce495d32046ef3ce7d0 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:12:45.366 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: c7f77f644b314d3e919832c13a150fa9 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:45.400 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: c7f77f644b314d3e919832c13a150fa9 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:45.401 10556 DEBUG oslo_concurrency.lockutils [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825" acquired by "nova.compute.manager.do_confirm_resize" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:45.402 10556 DEBUG nova.compute.manager [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Going to confirm migration 54 do_confirm_resize /usr/lib/python2.7/site-packages/nova/compute/manager.py:3460
2019-03-29 10:12:45.403 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 4fd0c5e602734e8cb5d89081f49f7d48 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:45.413 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4fd0c5e602734e8cb5d89081f49f7d48 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:45.414 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: e7d69d0bb17c4fa3ab6c46cfd3b2b0db exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:45.470 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: e7d69d0bb17c4fa3ab6c46cfd3b2b0db __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:45.474 10556 WARNING nova.image.glance [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:12:45.478 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: d2951711b20b409bad536f503e63ac7c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:45.597 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: d2951711b20b409bad536f503e63ac7c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:45.663 10556 DEBUG neutronclient.v2_0.client [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&binding%3Ahost_id=com58&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-d15da679-0f53-40c3-b7fd-5e0ec304e6e9 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:45.664 10556 DEBUG oslo_concurrency.lockutils [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Acquired semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:12:45.665 10556 DEBUG nova.network.neutronv2.api [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:12:45.665 10556 DEBUG nova.objects.instance [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'info_cache' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:12:45.666 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 072ea20a3da14e8a87ae2bf350f3f9d3 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:45.816 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 072ea20a3da14e8a87ae2bf350f3f9d3 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:45.820 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: bb104ad649734113b5ac8f09409a8c2b exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:45.829 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: bb104ad649734113b5ac8f09409a8c2b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:46.063 10556 DEBUG neutronclient.v2_0.client [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-d7d0980d-15b2-4e8e-8674-35ef0e6fe626 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:46.168 10556 DEBUG neutronclient.v2_0.client [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-7eb60fe7-7408-4bf4-b8b1-01ecdc0a6a3e _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:46.189 10556 DEBUG neutronclient.v2_0.client [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.11&port_id=b3249515-3aab-439f-ba9c-bc498756871a used request id req-27bb4fcc-c157-4d5e-a637-61b38a47a0b1 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:46.253 10556 DEBUG neutronclient.v2_0.client [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-d915707c-0234-4241-9a31-b9e5e2a911d5 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:46.446 10556 DEBUG neutronclient.v2_0.client [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-14bf410c-8a4d-446b-a112-16c1db2256f1 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:46.447 10556 DEBUG nova.network.base_api [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": true, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:12:46.449 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 9120484b12c94012b96ae466bd8a80ee exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:46.490 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 9120484b12c94012b96ae466bd8a80ee __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:46.491 10556 DEBUG oslo_concurrency.lockutils [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Releasing semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:12:46.492 10556 DEBUG oslo_concurrency.processutils [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): rm -rf /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_resize execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:12:46.511 10556 DEBUG oslo_concurrency.processutils [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "rm -rf /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825_resize" returned: 0 in 0.019s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:12:46.514 10556 DEBUG oslo_concurrency.lockutils [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.info" acquired by "nova.virt.libvirt.imagebackend.write_to_disk_info_file" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:46.515 10556 DEBUG oslo_concurrency.lockutils [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.info" released by "nova.virt.libvirt.imagebackend.write_to_disk_info_file" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:46.516 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 8b789c4d1abb437e85bfe667288a486b exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:46.533 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 8b789c4d1abb437e85bfe667288a486b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:46.541 10556 DEBUG nova.virt.libvirt.vif [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] vif_type=ovs instance=Instance(access_ip_v4=None,access_ip_v6=None,architecture='x86_64',auto_disk_config=True,availability_zone='nova',cell_name=None,cleaned=True,config_drive='True',created_at=2019-03-29T02:02:33Z,default_ephemeral_device=None,default_swap_device=None,deleted=False,deleted_at=None,device_metadata=<?>,disable_terminate=False,display_description='vm001',display_name='vm001',ec2_ids=<?>,ephemeral_gb=0,ephemeral_key_uuid=None,fault=<?>,flavor=Flavor(1),host='com58',hostname='vm001',id=24,image_ref='',info_cache=InstanceInfoCache,instance_type_id=1,kernel_id='',key_data=None,key_name=None,keypairs=<?>,launch_index=0,launched_at=2019-03-29T02:12:27Z,launched_on='com58',locked=False,locked_by=None,memory_mb=512,metadata={},migration_context=<?>,new_flavor=None,node='com58',numa_topology=<?>,old_flavor=None,os_type=None,pci_devices=<?>,pci_requests=<?>,power_state=1,progress=0,project_id='d4bbd972ca1b463ba028ccd1df983917',ramdisk_id='',reservation_id='r-x56iqcqr',root_device_name='/dev/vda',root_gb=1,security_groups=<?>,services=<?>,shutdown_terminate=False,system_metadata={boot_roles='admin',clean_attempts='1',image_architecture='x86_64',image_base_image_ref='',image_min_disk='1',image_min_ram='0'},tags=<?>,task_state=None,terminated_at=None,updated_at=2019-03-29T02:12:28Z,user_data=None,user_id='9e9e53917dda421083fa6af425c6bfbf',uuid=f5a19c94-1a45-4ea0-9386-77c10705c825,vcpu_model=<?>,vcpus=1,vm_mode=None,vm_state='resized') vif={"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": true, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} unplug /usr/lib/python2.7/site-packages/nova/virt/libvirt/vif.py:966
2019-03-29 10:12:46.541 10556 DEBUG nova.network.os_vif_util [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converting VIF {"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": true, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:413
2019-03-29 10:12:46.542 10556 DEBUG nova.network.os_vif_util [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converted object VIFBridge(active=True,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:425
2019-03-29 10:12:46.543 10556 DEBUG os_vif [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Unplugging vif VIFBridge(active=True,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') unplug /usr/lib/python2.7/site-packages/os_vif/__init__.py:112
2019-03-29 10:12:46.546 10556 DEBUG oslo.privsep.daemon [-] privsep: request[77878448]: (3, 'vif_plug_ovs.linux_net.delete_bridge', (u'qbrb3249515-3a', 'qvbb3249515-3a'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.546 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl delif qbrb3249515-3a qvbb3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.559 10556 DEBUG oslo.privsep.daemon [-] CMD "brctl delif qbrb3249515-3a qvbb3249515-3a" returned: 0 in 0.011s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.559 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qbrb3249515-3a down out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.566 10556 DEBUG oslo.privsep.daemon [-] CMD "ip link set qbrb3249515-3a down" returned: 0 in 0.009s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.567 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl delbr qbrb3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.581 10556 DEBUG oslo.privsep.daemon [-] CMD "brctl delbr qbrb3249515-3a" returned: 0 in 0.014s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.581 10556 DEBUG oslo.privsep.daemon [-] privsep: reply[77878448]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.583 10556 DEBUG oslo.privsep.daemon [-] privsep: request[77878448]: (3, 'vif_plug_ovs.linux_net.delete_ovs_vif_port', (u'br-int', 'qvob3249515-3a'), {'timeout': 120}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.583 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ovs-vsctl --timeout=120 -- --if-exists del-port br-int qvob3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.607 10556 DEBUG oslo.privsep.daemon [-] CMD "ovs-vsctl --timeout=120 -- --if-exists del-port br-int qvob3249515-3a" returned: 0 in 0.024s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.608 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link delete qvob3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.622 10556 DEBUG oslo.privsep.daemon [-] CMD "ip link delete qvob3249515-3a" returned: 0 in 0.015s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.622 10556 DEBUG oslo.privsep.daemon [-] Net device removed: 'qvob3249515-3a' out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.622 10556 DEBUG oslo.privsep.daemon [-] privsep: reply[77878448]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:46.623 10556 INFO os_vif [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Successfully unplugged vif VIFBridge(active=True,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a')
2019-03-29 10:12:46.625 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 88e01d9d990544b7add25741ce77e6f3 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:46.658 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 88e01d9d990544b7add25741ce77e6f3 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:46.659 10556 DEBUG oslo_concurrency.lockutils [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker.drop_move_claim" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:46.659 10556 DEBUG nova.objects.instance [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'migration_context' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:12:46.660 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 83dd65ad096b4996a1bdba64da65b474 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:46.677 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 83dd65ad096b4996a1bdba64da65b474 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:46.686 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: b7f575797a964c82b5a39d004ebc0511 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:46.716 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b7f575797a964c82b5a39d004ebc0511 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:46.718 10556 DEBUG nova.scheduler.client.report [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Refreshing aggregate associations for resource provider db732609-7867-486c-8e55-f52f70acfa62 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:12:46.752 10556 DEBUG oslo_concurrency.lockutils [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" released by "nova.compute.resource_tracker.drop_move_claim" :: held 0.093s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:46.757 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: e9800e85fd0441298a061997634831b3 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:46.785 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: e9800e85fd0441298a061997634831b3 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:46.789 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 201f4d91aa774c388ab2772eb9bda2a5 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:46.891 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 201f4d91aa774c388ab2772eb9bda2a5 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:46.893 10556 WARNING nova.image.glance [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:12:46.896 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 48de94a2e3ad4eb88a72334331018f2d exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:46.900 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 48de94a2e3ad4eb88a72334331018f2d __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:46.900 10556 DEBUG oslo_concurrency.lockutils [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825" released by "nova.compute.manager.do_confirm_resize" :: held 1.499s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:46.901 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-91504765-af51-4e93-8322-589354e306c1 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 32fbcacab99541edad02bf26d4079ec7 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:46.926 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 32fbcacab99541edad02bf26d4079ec7 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:53.766 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: a25cf84c6dfd4758b1950cc58c0c98fa exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:53.792 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a25cf84c6dfd4758b1950cc58c0c98fa __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:13:03.765 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 8ffa7787f90049779580557d7f25aec3 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:13:03.799 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 8ffa7787f90049779580557d7f25aec3 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407

